### ISSUE TITLE
follow up: Alert component. outer container not resizing correctly

### ISSUE THREAD

**Issue by alexandergrot** [divriots/story-to-design#100]
hey all,
this is a follow up to https://github.com/divriots/story-to-design/issues/86

when currently importing this story, it seems like some outer container doesn't grow with the text in horizontal space. so the text get's cut off.

![grafik](https://github.com/divriots/story-to-design/assets/102791744/766d8169-5e72-4948-80b6-ce6c8ec3e25b)

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/cTJHZkeCJCNZ1kgqi46Q/14kx3f218dij4p

**Comment by gqio** [comment]
Hello @alexandergrot 

Found the issue, pushed and merged the fix.
Release in progress should be availble in 10min it's only plugin side so you can just Reset the canvas.

Best.
