### ISSUE TITLE
Vertical Divider component

### ISSUE THREAD

**Issue by alexandergrot** [divriots/story-to-design#101]
hey all,

when importing this `Divider` component (vertical variation), the component doesn't grow as expected if the text gets longer.

in storybook (this is how it is expected):
![grafik](https://github.com/divriots/story-to-design/assets/102791744/ee4b8911-4083-4305-a99d-643194636289)

imported story to figma:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/cdcae813-70a2-4ec1-b58d-502ebb47f2bd)

text grows into the divider and the other text. i would expect the text on the left to grow and the container with it so the `Divider` element gets shifted to the right accordingly.

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/cTJHZkeCJCNZ1kgqi46Q/7ifwb6cjhyo

**Comment by gqio** [comment]
Hello @alexandergrot 

(Re-opening the ticket since my previous analysis was wrong)

I see that the content-box of the children is 0, is this normal ? there is only padding applied here.
![image](https://github.com/divriots/story-to-design/assets/1063530/17f9e1da-6095-4475-91c2-2a450db066de)

still digging

Best.

**Comment by alexandergrot** [comment]
hey @gqio ,
i can see the same, when removing the outer height of the container `<Box>` (basically [material-ui/box](https://mui.com/material-ui/react-box/)) and adding `flexItem` to the `<Divider>` (like in [this example](https://mui.com/material-ui/react-divider/#vertical-divider)) these elements you mention do have height. 

but the original problem stays the same:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/51af548a-a259-4efa-a3a3-32e686402e28)
(notice that the divider is a bit taller when the outer container height is removed)

**Comment by gqio** [comment]
Hello @alexandergrot 

After a debugging session why this not happening for autolayout here.
We are failing to compute the alignment on the children, leading us to not applying the autolayout.

The full container has height of 82 pixels
![image](https://github.com/divriots/story-to-design/assets/1063530/707421d2-6f2f-47e1-b675-e55521dfc9be)

Each texts has 64 pixels height, but we compute 83 (not sure why I need to dig here)
![image](https://github.com/divriots/story-to-design/assets/1063530/164bc6f6-681f-4b7b-9714-1f811f9b2d79)
![image](https://github.com/divriots/story-to-design/assets/1063530/32ecbfbb-e064-42a9-9a8b-844990eb268c)

And the divider has a height of 50pixels
![image](https://github.com/divriots/story-to-design/assets/1063530/ec274441-6ad2-4883-ab60-82ab6494fea6)

For autolayout we need at least one of the center|top|bottom to be found/computed

I don't know yet why we don't compute correctly the size for text containers here

I will keep you posted.

Best

**Comment by gluck** [comment]
(auto-closed due to merged fix, not released yet)

**Comment by gqio** [comment]
Hello @alexandergrot 

This one has been fixed in the latest release.
Agent update should be available in 10min.
Sorry for the delay.

Best.
