### ISSUE TITLE
Importing s2d variants from storybook.

### ISSUE THREAD

**Issue by sslPentia** [divriots/story-to-design#104]
Is it possible to import s2d variant properties from storybook instead of auto generated variants? I know it's possible to toggle advanced and manually insert JSON, but that’s just a very inconvenient workflow, especially for designers who may not have access to the codebase. Right now I need to import some random properties first, and then when I check for updates a new component pops up with the s2d variant properties from storybook, which is great, but as a result there are 2 components representing the exact same component in the overview.  

I hope the issue description makes sense, if not, feel free reach out.

---
Bug report identity: Please do not edit

Task path: 5SKyZds5XqqFF7zC08If/gyYMTQaeKwGlNcs9AImj/ej8xzj1n0qc0v

**Comment by gqio** [comment]
Hello @sslPentia 

Could you please reach us on https://story.to.design/chat maybe we can provide more detailed and reactive support.

In the meatime, if you imported all components with the automatic all import, yes you can edit imported component properties (even select another story as the base for the import). 
If you are not satisfied with the result even after the import you can ditch the component we generated for you and then do the import starting from scratch, meaning select a story first and then check only the properties you need to display as relevant visual variant.

Some pages where you might find some information 

https://story.to.design/docs/import-your-first-component

https://story.to.design/docs/setup-variants-basic

https://story.to.design/docs/setup-variants-advanced

I can also definitely help to configure your first component in the way you want it.

See you in discord 👋 
Best.

**Comment by sslPentia** [comment]
Hi Gregory,

Thank you for your response. I will try and reach you on discord then.

Bedste hilsner​​​​
Sebastian Søgaard Larsen
Consultant, Frontend
@ Pentia A/S
,
+4542211006<tel:+4542211006>

**Comment by gqio** [comment]
Don't hesitate to raise a new issue if you still encounter any other issue.

Best.
