### ISSUE TITLE
Component update error

### ISSUE THREAD

**Issue by elenabraeutigam** [divriots/story-to-design#106]
## Describe the problem ##
After a Storybook version update, there's an error when trying to update the chip component:
<img width="1264" alt="Screenshot 2023-09-08 at 13 53 07" src="https://github.com/divriots/story-to-design/assets/129752452/5da34ab8-2b7b-4dae-b6ff-5398b4210428">

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/lASnfr2aVzRQus6hWN1Y/1wwxizm11tg7vm

**Comment by gqio** [comment]
Hello @elenabraeutigam 

When I am trying to reproduce the parsing of the stories I got this 
![image](https://github.com/divriots/story-to-design/assets/1063530/d0db50b8-4622-4d64-9dc3-742a5154d2cf)

Does it sound familiar ? With this error the story.to.design agent cannot process anything.
Apparently this error is coming from your storybook.
Could you please confirm that you experience the same within the Iframe of this story ?

Best.

**Comment by nils-rohe** [comment]
Hi @gqio - when I look at this in our Storybook it all works fine, there is no problem. However, I experience the same issue @elenabraeutigam with this component and also with another one that previously imported without a problem too. It also works in the Storybook. So it seems this is rather an issue on your side.. Is there anything I can do to help debug this?

**Comment by nils-rohe** [comment]
The only thing the console spits out as soon as I click "reprocess story" is this:
![image](https://github.com/divriots/story-to-design/assets/108518250/574c9576-e138-4fc7-8522-7c1fcfb328a1)

**Comment by gqio** [comment]
Hello @nils-rohe

Thanks a lot for checking

Could you please to try to open the iframe of the story here and tell me if it's working or not ?
![image](https://github.com/divriots/story-to-design/assets/1063530/3130f45d-818b-4105-a7c1-a65847bf2892)
with the exact same story you reported.

With storybook sometimes the iframe (the render container of the story) does not work within a standalone iframe and only with the full storybook loaded (mostly due to missing lib not packaged correctly with the bundle of the iframe)

But we do have a solution for that, and I would like to know if this is coming from this before activating this option on your storybook on our side.

Best

**Comment by nils-rohe** [comment]
Ah okay. I tried and the components work without problem in the iframe too.

**Comment by gqio** [comment]
Ok I will try to understand what's going on then.
Honestly I don't know now, I might need help from @gluck or @muryoh :)

**Comment by muryoh** [comment]
Following up on Discord for quicker feedback!

**Comment by muryoh** [comment]
As I explained on discord, my understanding is that:
- there used to be a `color` arg on the story
- the component was imported with it
- `color` arg was removed - and the story fails to render when set

Immediate workaround is to edit the component to remove the `color` arg (it will be removed automatically upon editing and saving the conf will remove it from existing component variants)

We'll add a proper handling of args being removed in the product very soon

Cheers
Remy

**Comment by gqio** [comment]
Hello @elenabraeutigam 

Now when an arg has been removed you should see this error
![image](https://github.com/divriots/story-to-design/assets/1063530/1b13f905-305d-44d3-abd2-4f76b9af3451)

Best.

**Comment by gqio** [comment]
Hello @elenabraeutigam 

For recovering from this issue now:
1- you need to edit the variant (click on the ellipsis menu and Edit), 
2- reimport via the blue button inside the edit dialog to force update the arguments list
3- wait for processing.

Best
