### ISSUE TITLE
Preview of Component looks off

### ISSUE THREAD

**Issue by elenabraeutigam** [divriots/story-to-design#108]
## Describe the problem ##

For the Avatar component, the preview looks off:
<img width="1375" alt="Screenshot 2023-09-13 at 13 35 27" src="https://github.com/divriots/story-to-design/assets/129752452/1a79d400-52dd-4201-aa91-d36ca05570a2">

After updating, the canvas looks normal, though:
<img width="794" alt="Screenshot 2023-09-13 at 14 07 12" src="https://github.com/divriots/story-to-design/assets/129752452/80367a64-f569-4138-be78-72637c3b963a">

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/4yliGsRsjDiI50BV9Add/27ert711kx4fh

**Comment by gqio** [comment]
Hello @elenabraeutigam 

Could you please check if with the new version you have the same behaviour and just drop us a message here.

Thanks

**Comment by elenabraeutigam** [comment]
Hello @gqio 
So far, this issue didn't come up anymore.

**Comment by gqio** [comment]
Hello @elenabraeutigam 

Thanks for the heads up and thanks for reporting it.

Best
