### ISSUE TITLE
Unwanted change of colors

### ISSUE THREAD

**Issue by elenabraeutigam** [divriots/story-to-design#111]
## Describe the problem ##
The icon color of the TextField component is changed (for light theme) via the plugin even though this does not match our Storybook:
<img width="975" alt="Screenshot 2023-09-13 at 13 37 33" src="https://github.com/divriots/story-to-design/assets/129752452/57ac0e38-44f9-46c3-abf1-f25ef63675f0">
There are also some resizing issues after updating:
<img width="809" alt="Screenshot 2023-09-13 at 14 27 27" src="https://github.com/divriots/story-to-design/assets/129752452/103999d5-5bb8-4d75-8d27-aec6bb54fd4d">

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/4yliGsRsjDiI50BV9Add/1k6bmh3yt520y

**Comment by gqio** [comment]
Hello @elenabraeutigam 

This one has been fixed with the latest version

Best.
