### ISSUE TITLE
Select behaves wrong when changing the label or the helper text

### ISSUE THREAD

**Issue by nils-rohe** [divriots/story-to-design#112]
First of all, increasing the size of the Select leads to this situation:
![image](https://github.com/divriots/story-to-design/assets/108518250/762b0656-d0eb-4639-aacb-fbf8108d3ecc)

Similarly, adjusting the helper text leads to a similar situation:
![image](https://github.com/divriots/story-to-design/assets/108518250/b1c8af2a-1fa7-4de5-abdb-492d5d02a58d)

In our storybook the helper text is also aligned at the left and not the middle:
![image](https://github.com/divriots/story-to-design/assets/108518250/b54eaf71-91fa-4a88-8e21-f30817142300)
This is what it should look like:
![image](https://github.com/divriots/story-to-design/assets/108518250/09eb2f7d-4df4-4c3e-9a8d-9727594ab207)

Having a long label looks like this:
![image](https://github.com/divriots/story-to-design/assets/108518250/770e67f4-6831-4a61-97c8-4145bd5a30fd)
Looks like this in our storybook:
![image](https://github.com/divriots/story-to-design/assets/108518250/a57ebcaa-eeff-4628-8ec4-a5a0d5bb4b8d)

I might have raised some of these problems already before but there is no open issue anymore. Maybe some are related to this thread: https://discord.com/channels/744781525119139859/1129046890126774312

Let me know if there is something that I can try or if you need more info.

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/TpNtjdiUX2b6yPUi7ywR/404gay1remv1u

**Comment by gqio** [comment]
Hello @nils-rohe 

We just released some corrections about alignment lately

![image](https://github.com/divriots/story-to-design/assets/1063530/4a17447c-1f0f-4729-8e36-e7303958cfd1)

Not sure why we don't support the truncate of the text here.

**Comment by gqio** [comment]
Hello @nils-rohe 

With the latest release we fixed some of the issues:
- truncate of the text above the select
- left align of the text above the select
- left align of the select

Remains the left align of the text below the select.

We keep working on it.

**Comment by gqio** [comment]
Side note from @muryoh the truncate of the text is not 100% exactly like storybook, we lack the ellipsis but the text does not overflow anymore.

We are also working on it

**Comment by gqio** [comment]
@nils-rohe the alignment of the helper text is fixed now with the latest release of the plugin

**Comment by nils-rohe** [comment]
Thanks a lot for the updates! 
As you said @gqio the ellipsis is missing but text does not overflow anymore. 
From the other raised points - everything works except the component does not grow. It does not grow if I increase the container size. Also, in Storybook giving it a very long helperText increases the container and therefore also the dropdown but that does not happen in Figma.
