### ISSUE TITLE
Damaged Component

### ISSUE THREAD

**Issue by elenabraeutigam** [divriots/story-to-design#113]
## Describe the problem ##

The !minimized variants of this component got damaged from updating this story (resetting the canvas did not help):
<img width="988" alt="Select" src="https://github.com/divriots/story-to-design/assets/129752452/6a376a60-e3ef-46df-b90d-18e30a6d36e4">

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/LC0zXLpEQjHCrLX2iI2X/arya2i15pk37r

**Comment by gqio** [comment]
Hello @elenabraeutigam 

I am checking it.
Keep you posted.

Best.

**Comment by gqio** [comment]
Release is in progress should be available in 5 min-ish

**Comment by elenabraeutigam** [comment]
Unfortunately, I could only fix the rendering by deleting the Figma canvas and clicking "Add to canvas" in the plugin. 
But as mentioned in the past, this isn't great since I would then probably loose connection between the imported component and child components of that component.
Would be great if this could get fixed somehow.

**Comment by gqio** [comment]
> Unfortunately, I could only fix the rendering by deleting the Figma canvas and clicking "Add to canvas" in the plugin. But as mentioned in the past, this isn't great since I would then probably loose connection between the imported component and child components of that component. Would be great if this could get fixed somehow.

The reset canvas didn’t worked ?
If this is the case then I need to have a look here. Sorry for the inconvenience

**Comment by elenabraeutigam** [comment]
No that did not work. I also tried reprocessing the story, but that also didn't help.

**Comment by elenabraeutigam** [comment]
I had the same issue with our Textfield component. The preview of the plugin visualised the component correctly, but after updating it and even resetting the canvas, the component was still rendered wrong in the Figma canvas. Only deleting the canvas and adding it again fixed it.
