### ISSUE TITLE
Warped icon

### ISSUE THREAD

**Issue by elenabraeutigam** [divriots/story-to-design#114]
## Describe the problem ##
The icon on the left of the Alert text got warped in the Figma canvas even though the preview of the plugin shows it correctly:
<img width="1111" alt="AlertAction" src="https://github.com/divriots/story-to-design/assets/129752452/27668f2f-bbb7-4d35-a97c-2fe08089eaa1">

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/LC0zXLpEQjHCrLX2iI2X/16mvod71a6k2w

**Comment by gqio** [comment]
Hello @elenabraeutigam 

I am on it. The 3 issues are all related.
The issue is on the autolayout algo in the plugin.
Recently Figma changed the way they compute the sizings, now we need to force to recompute the calculation of dimensions to get the correct width/height.

Best

**Comment by gqio** [comment]
Release is in progress should be available in 5 min-ish
