### ISSUE TITLE
Damaged component items

### ISSUE THREAD

**Issue by elenabraeutigam** [divriots/story-to-design#115]
## Describe the problem ##
Several items of the Alert (Title) component (icon and both text elements) are damaged in the Figma canvas even though everything looks correct in the plugin preview:
<img width="965" alt="AlertTitle" src="https://github.com/divriots/story-to-design/assets/129752452/a485223b-3348-4205-a992-8a908f6da5c6">

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/LC0zXLpEQjHCrLX2iI2X/3z0aqkclavif

**Comment by gqio** [comment]
Hello @elenabraeutigam 

The icon is related to the other issues.

I am going to check for the text.

Best

**Comment by gqio** [comment]
Reopened because of automatic closing

**Comment by gqio** [comment]
Should be good now with the latest plugin release.
I was having trouble to reproduce the issue but the latest release fixed also the text.

Best
