### ISSUE TITLE
Tabs component: underline of active tab not behaving correctly

### ISSUE THREAD

**Issue by alexandergrot** [divriots/story-to-design#117]
hey all, 
when importing this Tabs component, the underline which marks the active tab doesnt't grow when the text of the tab title gets longer:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/aabb5793-8749-410f-9b21-1a803b6381b5)

also if another active tab is selected, the underline seems to go where the tab title of the active tab should be if the first tab title wasnt that long:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/e9142c70-e8e1-48f5-9875-968a284a43c2)

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/v87ftBRPngy3xXKuCpZP/1sf01id2jyvvj

**Comment by gqio** [comment]
Hello @alexandergrot 

Sadly we can't do magic here
The tab indicator is not linked at all by the layers, but in js.
See here
![image](https://github.com/divriots/story-to-design/assets/1063530/424ccc50-4335-49f5-8790-0666ae33144d)
