### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by pancheisor** [divriots/story-to-design#121]
## Describe the problem ##

---
Bug report identity: Please do not edit

Task path: ObILdV0S820TPTLWYtEm/NYlgwqNBu5wLqQ7EpsM7/kh31wf1oeiurc

**Comment by gqio** [comment]
Hello @pancheisor 

Before digging into this could you please let us know what we should have a look and what is not expected or incorrect ? Maybe a screenshot ?
It will help us a lot to have a look into your issue.

Best.
Greg.
