### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by jnjacobson** [divriots/story-to-design#124]
## Describe the problem ##

The hover state is not beeing rendered:

![image](https://github.com/divriots/story-to-design/assets/28321019/075198ac-2e51-4e92-bfac-83169076bb11)

We're using vue 3.

---
Bug report identity: Please do not edit

Task path: HsWfTgBhHaKocfKTquQ6/zY7vXwiWEReKToXMJhl3/50zerbolcg2v

**Comment by muryoh** [comment]
Hi @jnjacobson, sorry about that!
We've been notified of the issue and already have a fix pending for it - we just need to make the time to release it

Here's what the result for me locally with said fix:
![image](https://github.com/divriots/story-to-design/assets/1789748/02842945-4fcd-4dcd-bf65-4ba8538dbc56)


Cheers
Remy

**Comment by muryoh** [comment]
Hi, sorry it took some time but we just released a fix for it!
