### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by ananalnt** [divriots/story-to-design#125]
## Hi there, I am just trying out your plugin. I have two issues I am facing:
1st: I can import the components on the figma browser just fine, but nothing is imported when i try to do it on the figma desktop app.
2nd: when i import components (browser), it is imported in black and white and does not include the component colors.
Can you help me please,
thanks a lot,
Anais##

---
Bug report identity: Please do not edit

Task path: SjkcRcQEMBQ1PKvz3xFv/pdDUXmS4yqgEiLdbUhEK/1nmkvy610jmlvg

**Comment by muryoh** [comment]
Hi Anais!

For 1st point, it's not easy to say - I'm wondering if maybe you have an enterprise network with possibly a different setup than your browser?

For your 2nd point, this is the component I see at the moment:
![image](https://github.com/divriots/story-to-design/assets/1789748/893b1715-1544-4c11-9e20-bc57f20bf977)

What colors are you expecting to see here?

Looking forward to help you further!
I'm Remy on Discord (https://story.to.design/chat), username `remy.masson` - it may be faster to investigate live together

Cheers
Remy
