### ISSUE TITLE
Fluent Input component doesn't scale properly and the Label isn't editable.

### ISSUE THREAD

**Issue by Counsell1111** [divriots/story-to-design#128]
## Fluent Input component scale / label issue ##

Here's the Input from Fluent, no changes have been made to either the markup or the CSS, this is a bare-bones version of the standard Fluent Input and here are a few issues keeping it from being usable within Figma.

• Input component stops scaling with container at 200px.››
![Screenshot 2024-01-11 at 6 38 56 AM](https://github.com/divriots/story-to-design/assets/130077304/4f9ebb2d-67b1-4bed-804b-901ca2b8719a)
• Input label isn't editable.
![Screenshot 2024-01-11 at 6 40 57 AM](https://github.com/divriots/story-to-design/assets/130077304/2854a3bd-a539-439b-a173-a53a39e38389)

Bug report identity: Please do not edit

Task path: H5wicg5xvN61lpBgxzah/3NKrCZWygCYQfkbIyx0Z/zfdkzp9bx5d1

**Comment by gqio** [comment]
> • Input component stops scaling with container at 200px.››

I think the story of the component exposed in the story has a fixed size of 200px (400px in the official one)
Do you have some insight on how you see elements having a fixed width in web and being full resizable in Figma, what rules would make sense from your point of view ?

> • Input label isn't editable.

It should be exposed as an arg in the story for us to be able to map to a property in figma.
