### ISSUE TITLE
Avatar sizes aren't generated correctly in Figma

### ISSUE THREAD

**Issue by thais-divriots** [divriots/story-to-design#13]
## Describe the problem ##

When importing avatar from https://gitlab-org.gitlab.io/gitlab-ui/?path=/story/base-avatar--image&args=size:16 I get the option to bring the sizes args.
However, in Figma the size of the avatar isn't changing:
<img width="861" alt="Screenshot 2022-09-06 at 15 29 32" src="https://user-images.githubusercontent.com/89907220/188647772-fb77115a-9ef1-4fff-8935-0f5bae03968f.png">

---
Bug report identity: Please do not edit

Task path: rseXNKd8GDLpWaULhlYK/z9pUj3GpDilosbkySQ7z/odn3gxizm42r

**Comment by gluck** [comment]
As explained in https://story.to.design/docs/args-misrendering you'll find that this avatar story doesn't support (some) args through query params.
We have a workaround in place (which I'm going to fix to also support this case), but the root cause is from the storybook itself.
