### ISSUE TITLE
Fluent switch component doesn't have states and label can't be edited in properties.

### ISSUE THREAD

**Issue by Counsell1111** [divriots/story-to-design#130]
## Fluent switch component doesn't have states or properties available in Figma ##

Here's the menu list from Fluent, no changes have been made to either the markup or the CSS, this is a bare-bones version of the standard Fluent menu list and here are a few issues keeping it from being usable within Figma.

• Switch states aren't available in Figma property panel even though they're defined in storybook.
![Screenshot 2024-01-11 at 8 10 13 AM](https://github.com/divriots/story-to-design/assets/130077304/2b9fef2d-6379-48f9-a862-112465fc02de)
•Switch label can't be edited via the Figma properties panel.
 
Bug report identity: Please do not edit

Task path: H5wicg5xvN61lpBgxzah/3NKrCZWygCYQfkbIyx0Z/u8o7fj110b22j

**Comment by gqio** [comment]
Hello @Counsell1111 

> • Switch states aren't available in Figma property panel even though they're defined in storybook.

With the official Fluent UI and the help of our variant properties api

![image](https://github.com/divriots/story-to-design/assets/1063530/6711d66b-f017-44eb-a8ed-05280c0d06ac)

![image](https://github.com/divriots/story-to-design/assets/1063530/01cfc75e-46c0-40ff-8502-60486a83c403)

```json
{
  "initArgs": {
    ":selector": "#root > div > div > div", // To be able to select only  the root element you want, because of all extra layer added in the story
    ":actionSelector": "input" // which element should be clicked/tap
  },
  "variantProperties": [
    {
      "fromArg": ":tap" // create a boolean property based on the tap status
    }
  ]
}
```

or simply like this with your storybook

![image](https://github.com/divriots/story-to-design/assets/1063530/6de4ad99-833e-41ec-a015-e851004b5a52)


> •Switch label can't be edited via the Figma properties panel.

Should be exposed in the story as arg

Best
