### ISSUE TITLE
Fluent button component doesn't scale properly if there is an icon.

### ISSUE THREAD

**Issue by Counsell1111** [divriots/story-to-design#132]
## Fluent button component doesn't scale properly if there is an icon ##

Here's the button component from Fluent, no changes have been made to either the markup or the CSS, this is a bare-bones version of the standard Fluent button and here are a few issues keeping it from being usable within Figma.

 • Icon does not scale with button and label overlaps buttons icon when scaled.
![Screenshot 2024-01-11 at 11 10 04 AM](https://github.com/divriots/story-to-design/assets/130077304/d44e25f3-b765-427d-98bf-e477a375a585)

---
Bug report identity: Please do not edit

Task path: H5wicg5xvN61lpBgxzah/3NKrCZWygCYQfkbIyx0Z/1rc3tmr193xx4d

**Comment by muryoh** [comment]
Hi @Counsell1111, sorry about the late feedback!

I started looking into it
A first issue I'm seeing is one we've noticed with some fonts, where the font dimensions in the browser do not match the font dimensions in Figma, which throws story.to.design off when trying to determine autolayout coordinates

I'm on macOS myself and your storybook uses local fonts, can you just confirm whether you're on MacOS yourself too?

On it, will try to update asap 🙏

**Comment by muryoh** [comment]
Hi again, keeping you updated

We did some good progress on changing the way we compute autolayout to cope with this - it's a big work, but it should be available soon

This is what we get with the revamp on the button you reported:

![image](https://github.com/divriots/story-to-design/assets/1789748/27789b1b-c960-4a89-b3e9-a720cb13681d)

Sorry about the delayed feedbacks, autolayout is one tricky beast

Best regards
Remy

**Comment by muryoh** [comment]
Hi @Counsell1111, sorry about the late feedback! Last week we released a overhaul of the autolayout that should work and fix your situation

Please let me know if it doesn't!

Cheers
Remy

**Comment by muryoh** [comment]
(you will need to update your agent for the update to kick in)
