### ISSUE TITLE
Nested component not detected

### ISSUE THREAD

**Issue by georges-gomes** [divriots/story-to-design#133]
Reported by Stefan from `htwoo`

Storybook https://lab.n8d.studio/htwoo/htwoo-react/ 

---

The following situation - This component HOODocumentCard consists of the following pieces:
HooCardImage
HooCardLocation
HooCardTitle
HooCardFooter

and so on. When I import the card it reads the design of the element just as one single block not respecting the other components. I can import the individual pieces first but it don't reuse it later in the card.
Is there any way around this to build up a design system based on nested component, or is it always like this. That ever story counts as an individual component in Figma.

Could be that I do something wrong to. 

![image](https://github.com/divriots/story-to-design/assets/5250572/0b04c327-0e39-4d88-803e-bdc9b2bdecf9)

**Comment by StfBauer** [comment]
Thanks @georges-gomes 

The dedicated pieces under this card design / layout are directly inside the card:

![image](https://github.com/divriots/story-to-design/assets/5503835/2f9712e1-e3d6-4f46-bb9d-9f49d0a6988f)

This is the direct link to the component: 
https://lab.n8d.studio/htwoo/htwoo-react/?path=/docs/components-cards-document-card-hoodocumentcard--docs

You will also find the sources with this link:
https://github.com/n8design/htwoo/tree/49888135d4cf35db70e73850a6d6395a0727fee1/htwoo-react

**Comment by gqio** [comment]
Hello @StfBauer 

I imported in a random order all components you mentionned

We do have a bug on the component Image. Apparently we clean up too much the tree leading to not matching the components. But worked for me for the rest

![image](https://github.com/divriots/story-to-design/assets/1063530/b4fa897d-1a39-4b42-8eda-8e2b8623108f)

What you can do is to import in a random order too .. and once you detect something is wrong you can `Reset Canvas` on the component that is not respecting the Component hierachy/nesting. It will try to reprocess everything and try to match as much as possible with Component/Variant present on the canvas in Figma

I will keep you posted with the Image issue

Best

**Comment by gqio** [comment]
Found the issue for the Image.
I pushed a PR for that.

I will keep you posted when released.

**Comment by gqio** [comment]
Hello @StfBauer 

We released the new version.
Should be available in the latest plugin

Best.

PS: please reopen this one if it's not working as expected.
