### ISSUE TITLE
Unexpected property created when no valid properties are present 

### ISSUE THREAD

**Issue by katrynmc** [divriots/story-to-design#135]
## Describe the problem ##

When generating components that don't have any properties a property called "Property 1" with a value of "Default" is created in Figma.

---
Bug report identity: Please do not edit

Task path: 3eryT9IffgXOt5WqCE5l/KnJAodu15rfp5IsO5Qw6/1u23l0w14tizb4

**Comment by gqio** [comment]
Hello @katrynmc 

Yes Figma does not allow us to create a variant without any prop, this is the default behaviour of Variants in Figma

![image](https://github.com/divriots/story-to-design/assets/1063530/d1664ecb-b7ec-4c53-b078-9017d13cbcfe)

You can reproduce it by creating an empty frame, create component and then add a variant. You will get this Property1
And after adding a variant in Figma you cannot even delete this property, you can just rename it.

Do you expect from us to genera a component without any variant ? like this ?

![image](https://github.com/divriots/story-to-design/assets/1063530/a33dd9bf-024d-409e-89b8-a9b80d0b0979)

Best.

**Comment by katrynmc** [comment]
Hey @gqio thanks for the quick response, my expectation would be the latter example you mentioned , though I appreciate that that's not a true "variant". Happy to work with the former if that's what the API supports today.

**Comment by gqio** [comment]
Hello @katrynmc 

Sorry for late update but we released few weeks ago an option to take into account for component with mono variation and being able to not have any properties even if Figma used to set it by default

![image](https://github.com/divriots/story-to-design/assets/1063530/f91e4693-e84a-41e2-a591-ff386412e512)

Doc is here for available values: https://story.to.design/docs/setup-variants-advanced#type
It requires the advanced mode.

Happy to help if you encounter any issue with this.
Best.
