### ISSUE TITLE
Adding the viewports into import configuration does nothing (No args found)

### ISSUE THREAD

**Issue by mbugno** [divriots/story-to-design#139]
Adding the viewports into import configuration still does nothing for us. I've added the following config:
```
{
  "defaultImportConfiguration": {
    "initArgs": {}
  },
  "viewports": {
    "xl": 1440,
    "md": 768,
    "sm": 390
  },
  "styleMapping": {}
}
```

When I import a component, it still shows no :viewport option or even a section for the simulated states:
![image](https://github.com/divriots/story-to-design/assets/8027669/f29bac50-462d-4657-a938-fec9f218ec70)

Storybook version 7.6.4
newest version story.to.design plugin

We do not use args in our Storybook but all our components are responsive. Greg asked me to create an issue here, thread ID on discord was 1185182690153074748

**Comment by gluck** [comment]
Hi @mbugno indeed simulated states only appear for stories with args today.
Going to fix that, as they're definitely useable without args, will let you know when it's fixed.

Thanks for the report.
