### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by katrynmc** [divriots/story-to-design#145]
## Describe the problem ##
Alignment is not being processed correctly in the new version. 

We have an accordion-like component. In the coded component the text and arrow stack horizontally but in figma they are stacking vertically. I would expect that the stacking would match.

**Figma**
![Screenshot 2024-02-15 at 1 53 41 PM](https://github.com/divriots/story-to-design/assets/5421596/2e431219-b9f8-4b13-b398-d3dd85fa73a4)
**Code**
![image](https://github.com/divriots/story-to-design/assets/5421596/e7ec8924-aff5-4096-9c31-c8e2e1cf75b6)

---
Bug report identity: Please do not edit

Task path: 3eryT9IffgXOt5WqCE5l/oQWmpSbd7swxStJUQSh0/1mby8ewl3cvqf

**Comment by muryoh** [comment]
Hi, thanks for the report!

From my testing this seems to happen after an update or a reset, not on the initial add to canvas
Can you confirm this is your situation?

If it is, we have a fix that should be ready soon

**Comment by katrynmc** [comment]
@muryoh That seems to be correct! I tried deleting the component and re-adding it and that seems to have resolved the issue. Thank you!

**Comment by muryoh** [comment]
Alright, sorry about that, we'll fix the update process soon!

**Comment by muryoh** [comment]
We just released a new version of the agent which fixes this issue

Best regards
Remy
