### ISSUE TITLE
New component issue report (Nested icon)

### ISSUE THREAD

**Issue by jeremieparet** [divriots/story-to-design#147]
---
Bug report identity: Please do not edit

Task path: ep257UoJEMTnEDJeFpEl/xNheoeHmoaDi6ZJmPDqE/651g87143kvlp

**Comment by georges-gomes** [comment]
@jeremieparet can you please also "Report" the icon component separately? Thanks

**Comment by muryoh** [comment]
Hi @jeremieparet,

We just released a new version of story.to.design that fixes this.
You will need to reopen Figma for the plugin to refresh and update the agent to at least version v1.20.8 to benefit from it.
Then you may need to hit `Reset canvas` on the `IconButton` component to retrigger subcomponent detection:
![image](https://github.com/divriots/story-to-design/assets/1789748/2163ca04-37f5-485a-814a-02cb8b61dd9c)

Hopefully this fixes it for you, if it doesn't do not hesitate to reopen the issue

Best regards
Remy
