### ISSUE TITLE
Component not importing - comes up with 'Haserror'

### ISSUE THREAD

**Issue by YasminBL** [divriots/story-to-design#155]
When trying to import a component, it is appearing with red text 'Haserror' and it says that all of the variants failed.

![image](https://github.com/divriots/story-to-design/assets/117074096/368c1ce7-68b4-4de4-b52c-35ca181183b1)

---
Bug report identity: Please do not edit

Task path: 0L01ZDgKWSlbZEyhp84C/k7VvbdU5QlzLbvOkItCc/12nonzwsoyxdn

**Comment by gqio** [comment]
Hello @YasminBL 

Apparently when we are trying to replay your component there is an error on the storybook 

![image](https://github.com/divriots/story-to-design/assets/1063530/68fa37e3-9e99-4307-a23f-7675441af8a1)

This is the page we are trying to reach to extract the stories https://main--6544f5a4a5ace49c1fd2e589.chromatic.com/iframe.html?id=component-library-atoms-button--primary&viewMode=story

We also get some errors 
![image](https://github.com/divriots/story-to-design/assets/1063530/aad39f59-b2b1-4b60-9453-a0d4ffaac364)

Additionnally when I am using a simple tab in my browser I do not get any error 🤔 

Do you know where it could come from ? Should be located in your ThemeProvider. I found someone also experiencing this, maybe this https://stackoverflow.com/a/78130577 ?

I will continue to dig into this error.
I will keep you posted

Best.

**Comment by gqio** [comment]
Hello again @YasminBL 

I tried to setup a very simple one button and it worked.

![image](https://github.com/divriots/story-to-design/assets/1063530/ab6b0235-c5f3-466a-9630-db3449f7edb2)

Did you do a special configuration inside the plugin ? Or did you changed something in the meantime with your storybook between the report and now ?

Best.

**Comment by YasminBL** [comment]
Hi, I've passed on your comments to our engineering team who will be taking a look into the Storybook issue. 

I'm still getting the same error - I don't think I've used a special configuration. The below screenshot shows the options I've been choosing:

![image](https://github.com/divriots/story-to-design/assets/117074096/c1477ff7-a3d7-4b0b-beee-143bf29f07b8)

I've just tried it without 'Theme' and it works fine, so that's likely the problem.

**Comment by gqio** [comment]
> Hi, I've passed on your comments to our engineering team who will be taking a look into the Storybook issue.
> 
> I'm still getting the same error - I don't think I've used a special configuration. The below screenshot shows the options I've been choosing:
> 
> ![image](https://private-user-images.githubusercontent.com/117074096/312116324-c1477ff7-a3d7-4b0b-beee-143bf29f07b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTQ4MDcsIm5iZiI6MTcxMDI1NDUwNywicGF0aCI6Ii8xMTcwNzQwOTYvMzEyMTE2MzI0LWMxNDc3ZmY3LWEzZDctNGIwYi1iZWVlLTE0M2JmMjlmMDdiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNDQxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWVlM2ZlOWY1M2U1NDAyYTUxYzE3NDUzMGY2NjBlYjliY2M4ZTExMjQyNWI2N2I0MmJlMTY1ZDc1ZTk2NjlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nKH6HXZu6JpYdJVZveIqPROddxXiDFcoN21yMQ7pCwM)
> 
> I've just tried it without 'Theme' and it works fine, so that's likely the problem.

Thanks for checking with the Theme option unticked and confirm the issue.
I will wait for your engineering then.

Please keep me posted 🙏  would love to solve this issue.

Best.

**Comment by muryoh** [comment]
Hi @YasminBL, for your information - we're looking on our end as well, it is likely to be a problem on `story.to.design`

**Comment by gqio** [comment]
Hello @YasminBL 

After digging with @muryoh with your storybook.
Apparently you defined following our guide for themes some globalTypes.
And there is a conflict between the conf you made for making themes visible inside story.to.design and the theme switcher from your storybook.
It's on our side (the addon you are using didn't existed at the time we made the conf for globalTypes)
We need to fix this to be able load correctly the list of themes and support this new addon.
We will also fix the documentation for themes.

In the meantime if you want to make it work before we release a fix for this, you will need to fix the globalTypes definitions for themes.

As of today you have defined inside the globalTypes
```
"Demo Theme"
"High Contrast Theme"
"Life At Sea Theme"
```

And the decorators for the themes you are using is expecting these values

```
"demo"
"highContrast"
"lifeAtSea"
```

You can check you configuration via your hidden toolbar :) 
![image](https://github.com/divriots/story-to-design/assets/1063530/47e05672-8f74-4915-afc3-7d4f9046b5fc)

for the record here is the toolbar from the addon/themes from storybook and their values
![image](https://github.com/divriots/story-to-design/assets/1063530/dd9b39a4-e8ce-4614-b4ef-7211c54e9d90)


Once these changes made and deployed, the import of components with themes should work.

@muryoh or I will keep you posted when the fix will be released.

**Comment by gqio** [comment]
Hello @YasminBL 

fix has been merged and release is done.

If you want to test without redeploy on your side new storybook please tell me and I can force the reprocess of metadata of your storybook and then you can try after that to reimport your button.

Best.
