### ISSUE TITLE
Molecule component not recognizing Atom component

### ISSUE THREAD

**Issue by higginbg** [divriots/story-to-design#157]
After importing a Button atom and then a ButtonGroup molecule, Figma is not recognizing that the Button atom is in the molecule. I am only able to change the ButtonGroup variants and not the Button variants.

---
Bug report identity: Please do not edit

Task path: FfUBIcwJEI7Efd6DXJE2/3jybI6W31JBPf64Lg3A2/8sl2796nd59t

**Comment by muryoh** [comment]
This report contains the `Button` atom used in the `ButtonGroup` module where subcomponent matching is failing, closing it for cleanup and will follow up on https://github.com/divriots/story-to-design/issues/156
