### ISSUE TITLE
Issue with a multiline element

### ISSUE THREAD

**Issue by a-billet** [divriots/story-to-design#16]
## Describe the problem ##
Hi, 

I just exported one of my component and I have some issues with multiline text elements:
Here is my component in the storybook and the associated html (using Tailwind)
![image](https://user-images.githubusercontent.com/49640798/192757506-c55f96c5-205f-493c-84ca-a941604455cf.png)

```
<div class="flex flex-col p-2 h-full w-48 text-dark text-center font-bold">
    <p class="flex-1">Deposit your documents</p>
    <img src="..." alt="img" loading="lazy" class="h-16 w-16 m-auto my-4">
</div>
```
And here is the figma export:
![image](https://user-images.githubusercontent.com/49640798/192757800-c52292e8-cbce-483b-b112-6e8f0e27f721.png)

Could you please have a look at it?

---
Bug report identity: Please do not edit

Task path: 8X41n3YNsQf5al88dqAw/8vkouQUSWWFJEc00qNGc/1cinprmsnftw

**Comment by muryoh** [comment]
Hey @a-billet ,
Thanks for the report :+1: 
We're working on improving our support for auto-layout in Figma, and will probably tackle this issue along with it - will keep you updated!

**Comment by muryoh** [comment]
Hey @a-billet :hugs:
Should be fixed now! We didn't get to improve autolayout but text box wrapping is now supported :)
Let me know if that works for you!

Cheers
