### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by emmartin-design** [divriots/story-to-design#160]
Instead of a white fill, the plugin is pulling in a placeholder image style which isn't used in Storybook whatsoever. 

---
Bug report identity: Please do not edit

Task path: ecX1Ph13FF1JfcVM4CrE/oqpnnBWLSiIBI7Jqo7mH/1ferg4311vxgp8

**Comment by gqio** [comment]
Hello @emmartin-design 

Thanks a lot for reporting the issue.

Could you please tell us which button is not working, maybe with the screenshot of what you expect vs what you see.

Actually in this report there is 512 buttons, maybe you could also report less variations to highlight better what is not working? Not mandatory now but for the next report.

Best.

**Comment by emmartin-design** [comment]
Sure!
Any time there is a white fill, an image is applied to the background. This
image doesn't have any connection to Storybook, and is used as a
placeholder style in Figma only.

[image: image.png][image: image.png]

**Comment by gqio** [comment]
@emmartin-design apparently the copy paste of the images/screenshots didnt worked.

**Comment by emmartin-design** [comment]
Here's a link to a Figma file with the generated component from Storybook,
and its Figma counterpart:

https://www.figma.com/file/mKfMOxg9UZfBJvgWkHd4ZN/TEMP-test?type=design&node-id=0%3A1&mode=design&t=qRG2LRQnPdYheV4q-1

My guess is that because our design library uses variables for our colors,
the plugin used the only style with a white background... even though that
style isn't correct.
We don't house any customer-facing color values in our Figma styles.
They're all in variables.

**Comment by gqio** [comment]
> We don't house any customer-facing color values in our Figma styles.

Hello @emmartin-design 

Just checked but not sure from where this is coming from 🤔 

![image](https://github.com/divriots/story-to-design/assets/1063530/7c9a4c66-8574-46cb-9872-f8dbb9940f28)

Do you have some library or value for this variable ?

**Comment by emmartin-design** [comment]
Yes—this is a style in our design library. It's a placeholder style for
images in wireframes. It consists of two layers, a white layer and a png.

However, the white background we need is just a flat white. It's housed in
our Figma Variables.

**Comment by muryoh** [comment]
Hi @emmartin-design

We were able to identify and reproduce on our side, fix will be coming up soon

Thanks for letting us know!

**Comment by muryoh** [comment]
We just released a fix for it - the plugin needs to be updated (can be forced by refreshing the Figma tab)

You can choose the `Reset Canvas` option to force a redraw:
![image](https://github.com/divriots/story-to-design/assets/1789748/dbae2c7b-f8b8-49fd-8197-422cdc140e1c)


Cheers,
Remy
