### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by higginbg** [divriots/story-to-design#166]
Variants are not properly imported on buttons. Only a couple of buttons are properly filled.

<img width="874" alt="image" src="https://github.com/divriots/story-to-design/assets/30296062/d779dfc1-f677-4ae1-828d-54f1f7335550">

---
Bug report identity: Please do not edit

Task path: FfUBIcwJEI7Efd6DXJE2/gABnuX4hJD0gUimGXY4n/1kdfkmj18qhkrm

**Comment by muryoh** [comment]
Hi @higginbg,

Thanks for letting us know! Indeed it looks like a regression crept in

Having a look

**Comment by muryoh** [comment]
Found the issue, fix is in review
In the meantime if you want you can revert your `agent` to this version, https://github.com/divriots/story-to-design/releases/tag/v1.20.18, as the following one contains the regression

**Comment by higginbg** [comment]
@muryoh I reverted the agent, but it didn't seem to fix the colors.

Task path: FfUBIcwJEI7Efd6DXJE2/u5VGlhNZGdFBI9u84QiV/unff23p9d2kn

**Comment by muryoh** [comment]
Can you try `reprocess`ing the component?
Sorry, failed to mention that

**Comment by higginbg** [comment]
Ah ok that worked, thank you!

**Comment by muryoh** [comment]
Hey there, just to let you know we released a version with the fix 👍 Agent should prompt you for an upgrade when restarting it (or available at https://github.com/divriots/story-to-design/releases/tag/v1.20.22)

Thanks for letting us know!
