### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by leeritter** [divriots/story-to-design#168]
## Describe the problem ##
Imported hover state is receiving border that should only be associated with the focus state. If I remove "focus" from the simulated variants, then refresh the canvas, it displays the hover state correctly.

---
Bug report identity: Please do not edit

Task path: uD4XuR0Y9HHGSOS38ij9/a86E7p36oIbvQnmAYHOs/lkpc071mymom2

**Comment by leeritter** [comment]
Maybe some of this weirdness is due to the button being an Ionic component that uses "shadow parts" for some styles?

**Comment by muryoh** [comment]
Hi there,

We had a regression in the last release that probably explains it - the `story switching` basically does not work as expected and variants are generated from "wrong states"

If you're using the agent, you can try rolling back to this release: https://github.com/divriots/story-to-design/releases/tag/v1.20.18 . We will anyway most likely do a release today to fix it

Note that you will need to `reprocess` the components to benefit from the proper processing

Cheers
Remy

**Comment by muryoh** [comment]
Hey there, just to let you know we released a version with the fix 👍 Agent should prompt you for an upgrade when restarting it (or available at https://github.com/divriots/story-to-design/releases/tag/v1.20.22)

Please let us know if it fixes the issue, or we'll close the issue at some point later

**Comment by leeritter** [comment]
Great, thanks for the explanation there, @muryoh!
I'll look out for the fix to this in upcoming releases. If I'm using the agent, will it automatically update, or do I need to reinstall to get the latest release there?

**Comment by muryoh** [comment]
It should prompt you to update upon restart, which means actually quitting it and starting it
If it doesn't then yes a reinstall will be needed, but it should 👍

We actually did a release yesterday which contains the fix

**Comment by leeritter** [comment]
Cool, it looks fixed here. Thanks for the help!
