### ISSUE TITLE
Updating resetted property not working

### ISSUE THREAD

**Issue by jens-meisner** [divriots/story-to-design#169]
## Updating imported component ##
- imported a button story from storybook (button has a set borderWidth)
- imported component looks good
- changed the button story (removed the borderWidth)
- refreshed the imported component (by "Refresh canvas" button)
- imported component has still the previouly set border

By the way, if I change the borderWidth to a different number (and not undefined) the imported component is correctly updated.

---
Bug report identity: Please do not edit

Task path: o7ikEwELApDnbOUI8B6k/8cUxHdVkAQCctTUqstuS/1yykrg32d7r9n

**Comment by muryoh** [comment]
Hi @jens-meisner, sorry for the delayed feedback!

From what I can tell we do have logic to reset props
I have been trying to reproduce specifically with the `border-width`, but it seems to work fine on my end
Is this the workflow that is not working for you?

https://github.com/divriots/story-to-design/assets/1789748/6bb37093-6657-4aac-901a-635350b55775

Cheers,
Remy

**Comment by jens-meisner** [comment]
Hi Remy,

Thanks for your detailed response.

In my case I set the border-width to a number, e.g. 25, which worked.
Then I removed the border-width property (not set to 0 / zero) and synchronized, but the border-width was still 25.

Cheers,
Jens

**Comment by muryoh** [comment]
Are you able to reproduce with at will?
No matter what I try I don't seem to be able to reproduce, be it with my demo storybook or yours

Would you mind sharing a video with me, possibly on Discord if you prefer? (https://story.to.design/chat, my login is `remy.masson`)

Best
Remy

**Comment by jens-meisner** [comment]
[2024-05-03 14-22-42.zip](https://github.com/divriots/story-to-design/files/15200025/2024-05-03.14-22-42.zip)
Here is the video, hope it helps.
First change: (from 20) to “undefined” not working,
Second change to a different number (to 2) is working.

Cheers,
Jens

**Comment by muryoh** [comment]
Still no luck on my end

https://github.com/divriots/story-to-design/assets/1789748/3fcb17bd-876e-4477-a641-e4fa8fe2a861

Would you mind checking what is the reported border width on your button, in the devtools?
![image](https://github.com/divriots/story-to-design/assets/1789748/99f033a5-a421-46b6-813d-c47623dc1b20)

Maybe it would help if I was able to reproduce with your storybook source code directly, although I understand this may be private

**Comment by jens-meisner** [comment]
Hi Remy,

Today the behaviour was flaky. Sometimes it was updated correctly (also for “undefined”) and sometimes not.
The DevTools (on the storybook page) show a borderWidth of 1.
I added another video, but I am not sure, if it helps. As said before...flaky
[2024-05-06 08-51-49.zip](https://github.com/divriots/story-to-design/files/15217750/2024-05-06.08-51-49.zip)

**Comment by muryoh** [comment]
Hi @jens-meisner,

Good news - I have a lead! Sorry it took me some time
I believe there's a race condition specific to the `Refresh Canvas` action (specific to the `local mode`) where we "miss" the updated DOM

I'm looking into it 👍

**Comment by jens-meisner** [comment]
That sounds great! 👍

**Comment by muryoh** [comment]
Hi @jens-meisner , sorry about the late notice but we released a fix last week! (fix is mostly in the plugin, so if you reloaded your Figma tab since then you should benefit from the fix)

Hope it fixes your issue 👍 
Don't hesitate to reopen if it doesn't
