### ISSUE TITLE
New component issue report - filter button not openening

### ISSUE THREAD

**Issue by andreeeabb** [divriots/story-to-design#172]
## Describe the problem ##
I would like to import this page with each of the filters in open state. I tried with this path
---
Bug report identity: Please do not edit

Task path: WRqbNjeh3JQJI2q3UWHJ/vnFiS7hw7NRjiarOiLkW/73dj28excjar

**Comment by muryoh** [comment]
Hi @andreeeabb,

I see in your configuration you used the following `:actionSelector`:
```
#\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div.ids-filter-basic.--open > div.ids-filter__title.--desktop > button
```

It was really close to be correct - unfortunately, your components change their classes when opened, and you seem to have generated the selector with the component open.

This one should work:
```
#\\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div:nth-child(1) > div.ids-filter__title.--desktop > button
```

Giving you that JSON configuration:
```
{
  "initArgs": {
    ":actionSelector": "#\\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div:nth-child(1) > div.ids-filter__title.--desktop > button"
  },
  "variantProperties": [
    ":tap"
  ]
}
```

Unfortunately, we seem to be struggling with layer ordering there 😢 (Figma ordering really is not very intuitive!)
![image](https://github.com/divriots/story-to-design/assets/1789748/ea66d7ba-a0a4-4830-baeb-c2be4e633ca6)

A "workaround", is to capture only that component, which you can do with the following configuration:
```
{
  "initArgs": {
    ":selector": "#\\#main > section > section.plp-products__filter-container.--desktop",
    ":actionSelector": "#\\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div:nth-child(1) > div.ids-filter__title.--desktop > button"
  },
  "variantProperties": [
    ":tap"
  ]
}
```

Resulting in:
![image](https://github.com/divriots/story-to-design/assets/1789748/ea471350-0f65-4f85-bd63-d2c8a658a7ab)

I hope this helps 

Best regards
Remy

**Comment by andreeeabb** [comment]
Thank you very much,
Can you also send me maybe the configuration to capture only the component like in the image?
“A "workaround", is to capture only that component, which you can do with the following configuration:
image.png (view on web)<https://github.com/divriots/story-to-design/assets/1789748/ea471350-0f65-4f85-bd63-d2c8a658a7ab>”

Best regards
Andreea


***@***.***<https://www.spar-ics.com/>

Andreea BOGDAN, BSc
Product Engineer
<http://>

Mobile: +43 664 88971212
E-Mail: ***@***.******@***.***>

SPAR Business Services GmbH
Information & Communication Services
Europastrasse 3, 5015 Salzburg, Austria

<http://>

                ***@***.***
From: Remy ***@***.***>
Date: Friday, 10. May 2024 at 15:01
To: divriots/story-to-design ***@***.***>
Cc: BOGDAN Andreea (ICS480-ECI) ***@***.***>, Mention ***@***.***>
Subject: {EXT} Re: [divriots/story-to-design] New component issue report - filter button not openening (Issue #172)

Hi @andreeeabb<https://github.com/andreeeabb>,

I see in your configuration you used the following :actionSelector:

#\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div.ids-filter-basic.--open > div.ids-filter__title.--desktop > button

It was really close to be correct - unfortunately, your components change their classes when opened, and you seem to have generated the selector with the component open.

This one should work:

#\\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div:nth-child(1) > div.ids-filter__title.--desktop > button

Giving you that JSON configuration:

{

  "initArgs": {

    ":actionSelector": "#\\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div:nth-child(1) > div.ids-filter__title.--desktop > button"

  },

  "variantProperties": [

    ":tap"

  ]

}

Unfortunately, we seem to be struggling with layer ordering there 😢 (Figma ordering really is not very intuitive!)
image.png (view on web)<https://github.com/divriots/story-to-design/assets/1789748/ea66d7ba-a0a4-4830-baeb-c2be4e633ca6>

A "workaround", is to capture only that component, which you can do with the following configuration:
image.png (view on web)<https://github.com/divriots/story-to-design/assets/1789748/ea471350-0f65-4f85-bd63-d2c8a658a7ab>

I hope this helps

Best regards
Remy

**Comment by andreeeabb** [comment]
And maybe one last question, how can I open it  in a specific viewpart. I tried like this:

{
  "initArgs": {
    ":actionSelector": "#\\#main > aside > div.ids-plp-sidebar-mobile.ids-sidebar.--mobile > div > section.ids-plp-sidebar-mobile__filter > div > div.ids-mobile-button-overlay.mobile > button",
    ":viewports": "sm,md"
  },
  "variantProperties": [
    ":tap"
  ]
}


***@***.***<https://www.spar-ics.com/>

Andreea BOGDAN, BSc
Product Engineer
<http://>

Mobile: +43 664 88971212
E-Mail: ***@***.******@***.***>

SPAR Business Services GmbH
Information & Communication Services
Europastrasse 3, 5015 Salzburg, Austria

<http://>

                ***@***.***
From: BOGDAN Andreea (ICS480-ECI) ***@***.***>
Date: Monday, 13. May 2024 at 08:41
To: divriots/story-to-design ***@***.***>, divriots/story-to-design ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: {EXT} Re: [divriots/story-to-design] New component issue report - filter button not openening (Issue #172)
Thank you very much,
Can you also send me maybe the configuration to capture only the component like in the image?
“A "workaround", is to capture only that component, which you can do with the following configuration:
image.png (view on web)<https://github.com/divriots/story-to-design/assets/1789748/ea471350-0f65-4f85-bd63-d2c8a658a7ab>”

Best regards
Andreea

From: Remy ***@***.***>
Date: Friday, 10. May 2024 at 15:01
To: divriots/story-to-design ***@***.***>
Cc: BOGDAN Andreea (ICS480-ECI) ***@***.***>, Mention ***@***.***>
Subject: {EXT} Re: [divriots/story-to-design] New component issue report - filter button not openening (Issue #172)

Hi @andreeeabb<https://github.com/andreeeabb>,

I see in your configuration you used the following :actionSelector:

#\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div.ids-filter-basic.--open > div.ids-filter__title.--desktop > button

It was really close to be correct - unfortunately, your components change their classes when opened, and you seem to have generated the selector with the component open.

This one should work:

#\\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div:nth-child(1) > div.ids-filter__title.--desktop > button

Giving you that JSON configuration:

{

  "initArgs": {

    ":actionSelector": "#\\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div:nth-child(1) > div.ids-filter__title.--desktop > button"

  },

  "variantProperties": [

    ":tap"

  ]

}

Unfortunately, we seem to be struggling with layer ordering there 😢 (Figma ordering really is not very intuitive!)
image.png (view on web)<https://github.com/divriots/story-to-design/assets/1789748/ea66d7ba-a0a4-4830-baeb-c2be4e633ca6>

A "workaround", is to capture only that component, which you can do with the following configuration:
image.png (view on web)<https://github.com/divriots/story-to-design/assets/1789748/ea471350-0f65-4f85-bd63-d2c8a658a7ab>

I hope this helps

Best regards
Remy

**Comment by muryoh** [comment]
Hi @andreeeabb,

This configuration should allow you to capture only the component:
```
{
  "initArgs": {
    ":selector": "#\\#main > section > section.plp-products__filter-container.--desktop",
    ":actionSelector": "#\\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div:nth-child(1) > div.ids-filter__title.--desktop > button"
  },
  "variantProperties": [
    ":tap"
  ]
}
```

Regarding viewports, sure, it is completely possible
Here is a configuration that will import all viewports:
```
{
  "initArgs": {
    ":selector": "#\\#main > section > section.plp-products__filter-container.--desktop",
    ":actionSelector": "#\\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div:nth-child(1) > div.ids-filter__title.--desktop > button"
  },
  "variantProperties": [
    ":tap",
    ":viewport"
  ]
}
```
**However**, it is not working properly for most viewports because the page actually does not have that component on smaller viewports, as it disappears under 1024px width:

![image](https://github.com/divriots/story-to-design/assets/1789748/c1c11e20-f0b2-44c4-906f-f0fa938d6e8c)

Since your viewports are defined as follows:
```
  "viewports": {
    "xs": 375,
    "sm": 480,
    "md": 768,
    "lg": 1024,
    "xl": 1440
  }
```

You can limit importing to viewports >= 1024, using this configuration:
```
{
  "initArgs": {
    ":selector": "#\\#main > section > section.plp-products__filter-container.--desktop",
    ":actionSelector": "#\\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div:nth-child(1) > div.ids-filter__title.--desktop > button"
  },
  "variantProperties": [
    ":tap",
    {"fromArg": ":viewport", "values": ["lg", "xl"]}
  ]
}
```
Yielding:
![image](https://github.com/divriots/story-to-design/assets/1789748/5cf39760-d1d6-4640-bfc2-b9bd7e13f647)

I hope that helps

Best regards,
Remy

**Comment by andreeeabb** [comment]
Hi,
Thank you very much.
Yes, that component exists only after 1024, but this one should be for mobile and tablet (see below) . this should open an overlay actually but it-s not working

{
  "initArgs": {
    ":actionSelector": "#\\#main > aside > div.ids-plp-sidebar-mobile.ids-sidebar.--mobile > div > section.ids-plp-sidebar-mobile__filter > div > div.ids-mobile-button-overlay.mobile > button",
  },
  "variantProperties": [
    ":tap"
    ":viewports": "sm,md"

  ]



***@***.***<https://www.spar-ics.com/>

Andreea BOGDAN, BSc
Product Engineer
<http://>

Mobile: +43 664 88971212
E-Mail: ***@***.******@***.***>

SPAR Business Services GmbH
Information & Communication Services
Europastrasse 3, 5015 Salzburg, Austria

<http://>

                ***@***.***
From: Remy ***@***.***>
Date: Monday, 13. May 2024 at 11:48
To: divriots/story-to-design ***@***.***>
Cc: BOGDAN Andreea (ICS480-ECI) ***@***.***>, Mention ***@***.***>
Subject: {EXT} Re: [divriots/story-to-design] New component issue report - filter button not openening (Issue #172)

Hi @andreeeabb<https://github.com/andreeeabb>,

This configuration should allow you to capture only the component:

{

  "initArgs": {

    ":selector": "#\\#main > section > section.plp-products__filter-container.--desktop",

    ":actionSelector": "#\\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div:nth-child(1) > div.ids-filter__title.--desktop > button"

  },

  "variantProperties": [

    ":tap"

  ]

}

Regarding viewports, sure, it is completely possible
Here is a configuration that will import all viewports:

{

  "initArgs": {

    ":selector": "#\\#main > section > section.plp-products__filter-container.--desktop",

    ":actionSelector": "#\\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div:nth-child(1) > div.ids-filter__title.--desktop > button"

  },

  "variantProperties": [

    ":tap",

    ":viewport"

  ]

}

However, it is not working properly for most viewports because the page actually does not have that component on smaller viewports, as it disappears under 1024px width:

image.png (view on web)<https://github.com/divriots/story-to-design/assets/1789748/c1c11e20-f0b2-44c4-906f-f0fa938d6e8c>

Since your viewports are defined as follows:

  "viewports": {

    "xs": 375,

    "sm": 480,

    "md": 768,

    "lg": 1024,

    "xl": 1440

  }

You can limit importing to viewports >= 1024, using this configuration:

{

  "initArgs": {

    ":selector": "#\\#main > section > section.plp-products__filter-container.--desktop",

    ":actionSelector": "#\\#main > section > section.plp-products__filter-container.--desktop > div > div.desktop > div > div:nth-child(1) > div.ids-filter__title.--desktop > button"

  },

  "variantProperties": [

    ":tap",

    {"fromArg": ":viewport", "values": ["lg", "xl"]}

  ]

}

Yielding:
image.png (view on web)<https://github.com/divriots/story-to-design/assets/1789748/5cf39760-d1d6-4640-bfc2-b9bd7e13f647>

I hope that helps

Best regards,
Remy

**Comment by muryoh** [comment]
Pushing the product to the limit 😄 

So, here's a configuration that should work for `sm` and `md`:

```
{
  "initArgs": {
    ":selector": "#\\#main > aside > div.ids-plp-sidebar-mobile.ids-sidebar.--mobile > div",
    ":actionSelector": "#\\#main > aside > div.ids-plp-sidebar-mobile.ids-sidebar.--mobile > div > section.ids-plp-sidebar-mobile__filter > div > div.ids-mobile-button-overlay.mobile > button"
  },
  "variantProperties": [
    ":tap",
    {
      "fromArg": ":viewport",
      "values": [
        "sm",
        "md"
      ]
    }
  ]
}
```

However, I don't think it's currently possible to mix both those `sm` and `md` variants with the `lg` and `xl` one, because the component to be captured is not the same and we currently do not support that

Were you looking to have the same component in Figma for both `sm`, `md`, `lg` and `xl`?

**Comment by andreeeabb** [comment]
No, it is fine also if I do not have the same component. 😊 Thank you very much for you support. The only thing that is not working, is the import for default screen (without any tap,s or actions for 360px). Is it because of the storybook? New component issue reportbreakpoint 360 blank · Issue #173 · divriots/story-to-design (github.com)<https://github.com/divriots/story-to-design/issues/173>


***@***.***<https://www.spar-ics.com/>

Andreea BOGDAN, BSc
Product Engineer
<http://>

Mobile: +43 664 88971212
E-Mail: ***@***.******@***.***>

SPAR Business Services GmbH
Information & Communication Services
Europastrasse 3, 5015 Salzburg, Austria

<http://>

                ***@***.***
From: Remy ***@***.***>
Date: Monday, 13. May 2024 at 12:17
To: divriots/story-to-design ***@***.***>
Cc: BOGDAN Andreea (ICS480-ECI) ***@***.***>, Mention ***@***.***>
Subject: {EXT} Re: [divriots/story-to-design] New component issue report - filter button not openening (Issue #172)

Pushing the product to the limit 😄

So, here's a configuration that should work for sm and md:

{

  "initArgs": {

    ":selector": "#\\#main > aside > div.ids-plp-sidebar-mobile.ids-sidebar.--mobile > div",

    ":actionSelector": "#\\#main > aside > div.ids-plp-sidebar-mobile.ids-sidebar.--mobile > div > section.ids-plp-sidebar-mobile__filter > div > div.ids-mobile-button-overlay.mobile > button"

  },

  "variantProperties": [

    ":tap",

    {

      "fromArg": ":viewport",

      "values": [

        "sm",

        "md"

      ]

    }

  ]

}

However, I don't think it's currently possible to mix both those sm and md variants with the lg and xl one, because the component to be captured is not the same and we currently do not support that

Were you looking to have the same component in Figma for both sm, md, lg and xl?

**Comment by muryoh** [comment]
Glad I could help!

I will follow up on #173 👍
