### ISSUE TITLE
The plugin in Figma is not loading, stuck at 2/4

### ISSUE THREAD

**Issue by dalexiev00** [divriots/story-to-design#174]
When I start the story.to.design agent and go to figma to start the plugin it gets stuck to 2/4. I tried to restart the agent and sign out and in but it doesn't work. Please, help.

**Screenshots**
![image](https://github.com/divriots/story-to-design/assets/133855760/172a9c4a-bb3d-4263-8c67-92ac7768d12f)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 124.0.6367.207

**Comment by gluck** [comment]
Hi @dalexiev00 sorry to hear that.
I may need for details to troubleshoot your issue, if that feels too much for a GitHub discussion, feel free to jump on our [discord server](https://story.to.design/chat) and we'll continue there.

I'm assuming you're trying to connect to a local/private storybook, is that correct ? can you share it (e.g. as a zip), can be done privately on discord.
Did story.to.design ever work with this storybook or is it your first time trying ?

**Comment by dalexiev00** [comment]
Hello, thanks for response! We can go on discord but I will be available later today, I will write there and catch up.
And to the questions:
- yes, it's private storybook
- it worked before an update

**Comment by gluck** [comment]
As discussed on discord, downgrading and re-upgrading the agent fixed it.
Something's fishy but further troubleshooting is going to be difficult without reproduction, so closing for now.

Thanks !

**Comment by dalexiev00** [comment]
Thank you as well!
