### ISSUE TITLE
When css border properties are separated - the border is missing

### ISSUE THREAD

**Issue by dalexiev00** [divriots/story-to-design#175]
## Describe the problem ##

I noticed that when we define the properties of a border separately (like border-width, border-color, border-style) in figma the border is missing, but for short definition (like border: 1px solid black) it's perfectly fine. 
Could you check if you can do something about it? I can share more info if needed.

---
Bug report identity: Please do not edit

Task path: ep257UoJEMTnEDJeFpEl/1bA1JLkLYX3xr40WMSdS/wpa2qm1ywpfin

**Comment by gluck** [comment]
Hi @dalexiev00 
Issue doesn't really come from the fact that properties are separated, but that figma doesn't support mixed colors borders, so we can't fully implement it.
In your case maybe a bottom-only border (in figma) would be the closest to what you see in the web, but if you look closely on the edges, it will be different.

On the web you have:
<img width="150" alt="image" src="https://github.com/divriots/story-to-design/assets/604263/d07256a8-b216-40b8-8d0d-7077d509d548">

Such border is pretty tricky to implement exactly on figma.
We can probably use diamond gradients to make it work, so I'll have a look eventually, but just so you know, independent properties work just fine.
