### ISSUE TITLE
Not pulling through some colour variations to Figma

### ISSUE THREAD

**Issue by blair-gibson** [divriots/story-to-design#181]
When importing my button, the dark mode for blue & red is not pulling through.

---
Bug report identity: Please do not edit

Task path: SragfjsvOGj83URGpew0/wE3RMxnv6MKzcX99I8sx/1k0xtgo6qvly6

**Comment by muryoh** [comment]
Hi there,

My understanding is that this is now resolved with the patching of a ThemeProvider that would have side effects when switching themes (add classes to `body` but never removing them)

Don't hesitate to reopen if that's not the case!

Best regards
Remy
