### ISSUE TITLE
Nested Component not detected

### ISSUE THREAD

**Issue by tsryu** [divriots/story-to-design#185]
Hello again :)

I'm trying to use [nested components](https://story.to.design/docs/subcomponents) on Checkbox & CheckboxGroup.

But it does not show as a Checkbox instance inside CheckboxGroup.

|Storybook Code|Figma Component|
|---|---|
|<img width="317" alt="스크린샷 2024-06-28 오후 7 21 46" src="https://github.com/divriots/story-to-design/assets/1515041/9890831d-c464-4306-93a6-7330f02f0021">|<img width="469" alt="스크린샷 2024-06-28 오후 7 16 20" src="https://github.com/divriots/story-to-design/assets/1515041/ccce5b5e-b109-4f43-9b32-d85d806bae4f">|

Radio & RadioGroup have the same structure as Checkbox & CheckboxGroup.
But Radio is recognized as instance.

|Storybook Code|Figma Component|
|---|---|
|<img width="269" alt="스크린샷 2024-06-28 오후 7 22 25" src="https://github.com/divriots/story-to-design/assets/1515041/84f2552a-ad66-4a56-91dd-cea63c8d297b">|<img width="465" alt="스크린샷 2024-06-28 오후 7 15 36" src="https://github.com/divriots/story-to-design/assets/1515041/1e53965c-f9f4-482f-8c29-1d0e03e7ebbf">|

As I checked the logs, there seems no problem with import process.
Do you know why it's not recognized as a nested component?

---
Bug report identity: Please do not edit

Task path: 25Eqsg9Q3TpEpyGjd17z/lBxhIMbtM3yBbAUxTqc6/27ci5o1y6rjcj

**Comment by muryoh** [comment]
Hello again 😄 

There might be a problem with the subcomponent matching
Would you mind also reporting the checkbox component in the plugin? That way we can have a look at why the Checkbox Group does not use the Chechbox as a component 🙏

**Comment by tsryu** [comment]
Thanks for your help..!

This is Checkbox report code
Task path: 25Eqsg9Q3TpEpyGjd17z/lBxhIMbtM3yBbAUxTqc6/1qvxkxo186fe7k

Let me show you Checkbox and Radio code too.

![스크린샷 2024-07-01 오전 10 56 11](https://github.com/divriots/story-to-design/assets/1515041/f4cf4dda-287e-4e24-b2ac-f8b7a07bc960)

As you see the code above, these components are wrapped to recognize it as a boolean prop. (e.g.- showThumbnail, showSubText, showBadge)
Please note :)

**Comment by muryoh** [comment]
Hi @tsryu , I'm happy to report we identified a bug in the subcomponent matching - we'll release a fix soon 👍 
![image](https://github.com/divriots/story-to-design/assets/1789748/394914bd-2237-41da-93d1-480ba15bd5f5)

**Comment by muryoh** [comment]
We'll release the fix soon 🤗

**Comment by muryoh** [comment]
Just did, make sure to reload your Figma tab to benefit from the latest plugin release!

Best regards
Remy

**Comment by tsryu** [comment]
Thanks for your help 🥇 
Let me update the plugin
