### ISSUE TITLE
Typography issue report (report 1 of 3 for "SimpleCheckboxes")

### ISSUE THREAD

**Issue by libbyberrie-pursuit** [divriots/story-to-design#188]
Hi divRIOTS team 
This is the Sub-Sub component that **is** currently being detected by SimpleCheckboxes. 
---
Bug report identity: Please do not edit

Task path: RiwI6gUcT2kzA6cWOuZs/AKb0uCwA1Dg2IPjgNdef/1yu0p6fevdcol

**Comment by muryoh** [comment]
Thanks for the report - closing for cleanup
