### ISSUE TITLE
Checkbox component issue report (report 2 of 3 for SimpleCheckboxes)

### ISSUE THREAD

**Issue by libbyberrie-pursuit** [divriots/story-to-design#189]
Hi divRIOTS team, 
This is the sub-component that **is not** being detected as a subcomponent in the parent SimpleCheckboxes component)

I realised i forgot to mention earlier - some time before finishing SimpleCheckboxes' integration i ended up changing the name of the component - i'm wondering if that may have meant it was considered a "new" component as the names didn't match up. 

---
Bug report identity: Please do not edit

Task path: RiwI6gUcT2kzA6cWOuZs/AKb0uCwA1Dg2IPjgNdef/1qvyrin1n80j9h

**Comment by muryoh** [comment]
Thanks for the report - closing for cleanup
