### ISSUE TITLE
SimpleCheckboxes component issue report (Part 3 of 3 for SimpleCheckboxes)

### ISSUE THREAD

**Issue by libbyberrie-pursuit** [divriots/story-to-design#190]
Hi divRIOTS team, 
This is the last part of the reports requested for my Discord support ticket. This is where i'm not detecting the middle `Checkbox` component. 

Thanks so much in advance for your help!
---
Bug report identity: Please do not edit

Task path: RiwI6gUcT2kzA6cWOuZs/AKb0uCwA1Dg2IPjgNdef/1uzcncx1595kqv

**Comment by muryoh** [comment]
Discussed on Discord (https://discord.com/channels/744781525119139859/1271354109131231286/1271354109131231286)

**Comment by muryoh** [comment]
Followed up and fixed on Discord 👍
