### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by katie-schmidt16** [divriots/story-to-design#193]
## This component is not recognizing the fonts we are using. The font for the heading should be Decimal and the font for the body copy should be BridgestoneType. I do have these installed on my computer and they are working in other components just not this one. ##

---
Bug report identity: Please do not edit

Task path: hpPpNB3AXDmRHPrweEFJ/cUNmuxZThtvrFAucHLCq/vyyrb21i9i0zu

**Comment by muryoh** [comment]
Hi @katie-schmidt16, thanks for the report!

Interestingly enough, it seems to be related to the version of Chromium we use to capture the stories. We are currently using Chromium 124, and in it the component does not actually load correctly. I also tried with Chromium 123 and I'm seeing the same results:
![image](https://github.com/user-attachments/assets/490be0cf-48ed-4449-bbcc-7a91d12479a4)

On the left, in my day-to-day browser (Brave), on the right, Chromium 123/124 (some other versions are very probably impacted too, only tested those two):
![image](https://github.com/user-attachments/assets/97de0701-38cd-416f-a98e-8fee78e07ecc)

I'm looking into upgrading the browser version we're using, but I thought you'd want to know some of your users could be impacted

Will keep you updated!
Remy

**Comment by muryoh** [comment]
Will be fixed in the next release, I'll keep you updated, should be soon :+1:

**Comment by muryoh** [comment]
Hi @katie-schmidt16,

We released last Friday a new version that should fix those issues
To benefit from the fix on your already imported components, you will need to ask for a `Reprocess` of those components:

![2024-09-23_11-30](https://github.com/user-attachments/assets/89cef7e8-f969-4502-bb30-bd3537df4a02)

Hope that helps
Best regards,
Remy
