### ISSUE TITLE
Checkbox is not importing correctly

### ISSUE THREAD

**Issue by katie-schmidt16** [divriots/story-to-design#194]
## Our checkbox component is not importing correctly. 

Some of the issues are: 
- Bottom padding of the checkbox is incorrect
- The checkbox fill is incorrect, should not have fill
- The md label has 0.59px bottom padding
- The checkbox container is not centered with the state container
- The checkmark and indeterminate icons have no fill and are the wrong size ##

---
Bug report identity: Please do not edit

Task path: hpPpNB3AXDmRHPrweEFJ/cUNmuxZThtvrFAucHLCq/r8msrmy1cztl

**Comment by katie-schmidt16** [comment]
Similar issues we are having with another component: https://github.com/divriots/story-to-design/issues/195

**Comment by muryoh** [comment]
Hi @katie-schmidt16 

This is very related to #193: the component does not load properly in older versions of Chrome

Here's what it will look like after the next release (left before, right after) which we're trying to roll out today but we have a few other improvements in the works:

![image](https://github.com/user-attachments/assets/fd17bbe7-8b0d-4930-855b-c204598223a3)

**Comment by muryoh** [comment]
Hi @katie-schmidt16,

We released last Friday a new version that should fix those issues
To benefit from the fix on your already imported components, you will need to ask for a `Reprocess` of those components:

![2024-09-23_11-30](https://github.com/user-attachments/assets/24a861f1-2376-49c5-809c-0f956f8cd263)

Hope that helps
Best regards,
Remy
