### ISSUE TITLE
Radio button is not importing correctly

### ISSUE THREAD

**Issue by katie-schmidt16** [divriots/story-to-design#195]
## Our radio button component is not importing correctly.
Some of the issues are:
• Bottom padding of the radio button is incorrect
• The radio button container is not centered with the state container
• The dot icons have no fill and are the wrong size ##

---
Bug report identity: Please do not edit

Task path: hpPpNB3AXDmRHPrweEFJ/cUNmuxZThtvrFAucHLCq/csdd7s1ovnf7i

**Comment by katie-schmidt16** [comment]
Similar issues we are having with another component: https://github.com/divriots/story-to-design/issues/194

**Comment by muryoh** [comment]
Hi @katie-schmidt16 

This is very related to #193: the component does not load properly in older versions of Chrome

Here's what it will look like after the next release (left before, right after) which we're trying to roll out today but we have a few other improvements in the works:
![image](https://github.com/user-attachments/assets/e2b15ca2-a72a-4e6e-af0a-6bd9e56f656d)

**Comment by muryoh** [comment]
Hi @katie-schmidt16,

We released last Friday a new version that should fix those issues
To benefit from the fix on your already imported components, you will need to ask for a `Reprocess` of those components:

![2024-09-23_11-30](https://github.com/user-attachments/assets/f270645e-c378-4d2a-81c6-80ccfcf1d580)


Hope that helps
Best regards,
Remy
