### ISSUE TITLE
Fonts not linking to styles

### ISSUE THREAD

**Issue by katie-schmidt16** [divriots/story-to-design#198]
## The font styles are not automatically linking. We were able to get the colors to work but not the fonts. Can you help us figure out why this is? Thanks!  ##

---
Bug report identity: Please do not edit

Task path: hpPpNB3AXDmRHPrweEFJ/nsMl6i7dTdqysb1SpE2d/1p57tp111fgr73

**Comment by georges-gomes** [comment]
Hi! I got an email from "Linda" with a similar request. Is that the same group and same storybook?

**Comment by j9981** [comment]
Hi Georges, it's not the same group or storybook.

**Comment by georges-gomes** [comment]
This is not a feature available today but with 2 teams requesting it we will investigate feasibility 👍

**Comment by j9981** [comment]
In the story to design [doc](https://story.to.design/docs/matching-styles), it says it currently only matches the following styles, and "text" is one of them. Do you mean the feature is not yet released?

**Comment by georges-gomes** [comment]
I wrote this piece of doc so...
Maybe I'm wrong now - maybe there is a bug.
Let me get back to you

**Comment by georges-gomes** [comment]
I'm wrong :)

I just tested the feature and it's working.
But, the text style need to match perfectly in every detail and this can be hard.

Can you please `create style` from a text node that story.to.design has created and compare it with your text style.

Please send over the difference to see if we can find what we can improve to make a match.

Thanks
Georges

**Comment by georges-gomes** [comment]
The main issue here I think is that the text style in Figma may not have the same `line-height` and `letter-spacing` than in storybook. This is aggravated when you don't have the same font in Figma that match perfectly because we adjust `line-height` and `letter-spacing` to compensate the differences between the fonts.

**Comment by katie-schmidt16** [comment]
Hi, yes this is the problem. The line height and letter spacing are different than our text style. We will investigate this. Thank you.

**Comment by rmonroy-icrossing** [comment]
Hi, It seems to be the way Chromium renders the units of measurement. In the first example, we can see how in Google Chrome we set the line-height value to 130%. In the second example, when switching to Chrome's computed mode, the value has been transformed to 20.8. Chrome performs the conversion to use the desired units of measurement. As far as I understand, story.to.design uses Chromium.

Given that, it doesn’t seem to be an issue but rather the default behavior of how it works.

![Screenshot 2024-10-03 at 1 31 27 PM](https://github.com/user-attachments/assets/bea4a960-1b2d-40c4-aed2-c284c6b7b27c)
![Screenshot 2024-10-03 at 1 32 59 PM](https://github.com/user-attachments/assets/f71604f9-bc24-4b2f-83cb-542b5872a8d4)

**Comment by j9981** [comment]
That being said, what should we do to make sure it doesn't get convert to something like a 20.8 from 130%?

**Comment by georges-gomes** [comment]
We will be looking at this issue.
If we can match properly, regardless of the unit, I think that what is expected.
The only question we have to answer is either of not we can technically do it 💪

**Comment by gqio** [comment]
Hello @j9981 

We released a fix for you issue, please use the reprocess and repaint option in the menu of the component.

Best.
