### ISSUE TITLE
Button Default State

### ISSUE THREAD

**Issue by katie-schmidt16** [divriots/story-to-design#201]
## Hi, I'm wondering if you can help me figure out why the default state is showing the button's loading state. We were having trouble with the default state in a r[ecent other ticket](https://github.com/divriots/story-to-design/issues/199) and were able to get it fixed for that component but for the button we are getting slightly different results.  ##

---
Bug report identity: Please do not edit

Task path: hpPpNB3AXDmRHPrweEFJ/O9mdWr8t8Mik022ELj1i/2ofrffyck7fg

**Comment by muryoh** [comment]
Hi @katie-schmidt16,

This is what I'm seeing:
![image](https://github.com/user-attachments/assets/b2272b8c-1b8a-4deb-8989-351308e6110f)

Are you getting something different?

**Comment by katie-schmidt16** [comment]
Yes, I'm getting some very strange results for this one. A lot of the states are showing loading state and the right icon is showing by default. What you sent is exactly what I would like it to look like.
<img width="432" alt="Screenshot 2024-10-22 at 6 56 58 AM" src="https://github.com/user-attachments/assets/b7a08433-8488-4fd2-8e38-5248ff49f175">

**Comment by katie-schmidt16** [comment]
Ok I was able to get this fixed for the button. Will continue trying with the checkbox. Thanks.
