### ISSUE TITLE
Radio button missing fill

### ISSUE THREAD

**Issue by katie-schmidt16** [divriots/story-to-design#202]
## Hi, Could you help me figure out why the radio button dot icon doesn't have a fill for the focus state? All other states are importing correctly and everything look as expected in Storybook. ##

---
Bug report identity: Please do not edit

Task path: hpPpNB3AXDmRHPrweEFJ/O9mdWr8t8Mik022ELj1i/1dx6tmpnrinpn

**Comment by katie-schmidt16** [comment]
Ok I'm noticing this same problem on other components as well. It's anywhere the icon is supposed to be #00000

**Comment by muryoh** [comment]
Good spot!
Should be fixed in the next release :ok_hand: 
![image](https://github.com/user-attachments/assets/edf86482-f021-4ad0-a404-854d626afb6d)

**Comment by muryoh** [comment]
Released a few hours ago! Needs a reprocess to benefit from the fix :pray:
