### ISSUE TITLE
Logo component isn't working correctly

### ISSUE THREAD

**Issue by katie-schmidt16** [divriots/story-to-design#203]
## Hi, Could you help me figure out why our logo component isn't importing correctly? Some of components are wrong and others are missing their fill. ##

---
Bug report identity: Please do not edit

Task path: hpPpNB3AXDmRHPrweEFJ/O9mdWr8t8Mik022ELj1i/horzm910pun18

**Comment by muryoh** [comment]
Hi @katie-schmidt16

Yes I can see the problem
This happens because there is both an arg called `brand` and a global named `brand` - currently story.to.design tries to change the global but in your case you wanted it to switch the story arg

Having a look

**Comment by muryoh** [comment]
Should be fixed with the last release - please use the `Reprocess story` on the Logo component and update it to benefit from the fix :pray:
