### ISSUE TITLE
Checkbox component isn't nested

### ISSUE THREAD

**Issue by katie-schmidt16** [divriots/story-to-design#204]
## Similar to this [ticket](https://github.com/divriots/story-to-design/issues/200), our checkbox component isn't nested in the checkbox group component. Could you please help me solve this? ##

---
Bug report identity: Please do not edit

Task path: hpPpNB3AXDmRHPrweEFJ/O9mdWr8t8Mik022ELj1i/1aacx4eudu584

**Comment by muryoh** [comment]
Hi @katie-schmidt16

I can see where this is coming from, fix is coming :+1: 

I have a workaround but it involves manual configuration on your storybook and it will become useless after the next release, so it will effectively pollute the configuration for nothing. Let me know if you cannot wait :smile: 

Cheers
Remy

**Comment by katie-schmidt16** [comment]
@muryoh Thanks! Should be no problem to wait for the next release. When is that planned to go out?

**Comment by muryoh** [comment]
We actually released two hours ago

There's one small thing though: to benefit from that fix, we need to reprocess the "storybook configuration". This will happen automatically when the storybook is updated - I can also force it manually, which will trigger the same update process.

Is it ok if i do that now? (only expected impact is that all imported components will need to be reprocessed just like when the storybook is updated)

**Comment by katie-schmidt16** [comment]
yes that's fine!

**Comment by muryoh** [comment]
done, please restart your plugin :pray:

**Comment by katie-schmidt16** [comment]
This is working now! Thanks!
