### ISSUE TITLE
Checkbox states aren't working

### ISSUE THREAD

**Issue by katie-schmidt16** [divriots/story-to-design#208]
## I'm able to get the states to look correct for the empty checkbox but as soon as I add in the checked and indeterminate, all the states show as disabled. ##

---
Bug report identity: Please do not edit

Task path: hpPpNB3AXDmRHPrweEFJ/NIdTSBCUeUpHiiLbGcQJ/ey8iuxqu7w2v

**Comment by muryoh** [comment]
Indeed, that's because I misled you in another issue (https://github.com/divriots/story-to-design/issues/199#issuecomment-2425977405): other arguments within an advanced arg do not default to false. Sorry about that!

Here's the proper configuration that should work as expected:
```
{
  "initArgs": {},
  "variantProperties": [
    "size",
    "error",
    {
      "name": "feedback",
      "values": [
        {
          "name": "checked",
          "withArgs": {
            "checked": true,
            "indeterminate": false
          }
        },
        {
          "name": "unChecked"
        },
        {
          "name": "indeterminate",
          "withArgs": {
            "indeterminate": true,
            "checked": false
          }
        }
      ]
    },
    {
      "name": "state",
      "values": [
        {
          "name": "default"
        },
        {
          "name": "hover",
          "withArgs": {
            ":hover": true,
            ":focus": false,
            "disabled": false
          }
        },
        {
          "name": "focus",
          "withArgs": {
            ":hover": false,
            ":focus": true,
            "disabled": false
          }
        },
        {
          "name": "disabled",
          "withArgs": {
            ":hover": false,
            ":focus": false,
            "disabled": "true"
          }
        }
      ]
    }
  ]
}
```

**Comment by katie-schmidt16** [comment]
Ok it's so close! I'm still getting a random few of the default states showing as disabled.
![Frame 2](https://github.com/user-attachments/assets/3b5a5a67-e985-401b-88e1-4ed88154d204)
{
  "initArgs": {},
  "variantProperties": [
    "size",
    "error",
    {
      "name": "feedback",
      "values": [
        {
          "name": "checked",
          "withArgs": {
            "checked": true,
            "indeterminate": false,
            "unChecked": false
          }
        },
        {
          "name": "unChecked",
          "withArgs": {
            "checked": false,
            "indeterminate": false,
            "unChecked": true
          }
        },
        {
          "name": "indeterminate",
          "withArgs": {
            "indeterminate": true,
            "checked": false,
            "unChecked": false
          }
        }
      ]
    },
    {
      "name": "state",
      "values": [
        {
          "name": "default",
          "withArgs": {
            ":hover": false,
            ":focus": false,
            "disabled": false
          }
        },
        {
          "name": "hover",
          "withArgs": {
            ":hover": true,
            ":focus": false,
            "disabled": false
          }
        },
        {
          "name": "focus",
          "withArgs": {
            ":hover": false,
            ":focus": true,
            "disabled": false
          }
        },
        {
          "name": "disabled",
          "withArgs": {
            ":hover": false,
            ":focus": false,
            "disabled": "true"
          }
        }
      ]
    }
  ]
}

**Comment by katie-schmidt16** [comment]
Nevermind, it's working correctly! Thank you!
