### ISSUE TITLE
Button font and spacing issues

### ISSUE THREAD

**Issue by katie-schmidt16** [divriots/story-to-design#210]
## Hi, our fonts still aren't automatically connecting to the font styles for any of the components. And then I think because of this, the padding on our button and some of the other components is incorrect. ##

---
Bug report identity: Please do not edit

Task path: hpPpNB3AXDmRHPrweEFJ/sfVQjZ45JjFtHNbBsv90/1v5rrz3y2gov0

**Comment by katie-schmidt16** [comment]
Also, related to this same component the loading icon fill isn't showing.

**Comment by muryoh** [comment]
Hi @katie-schmidt16, sorry to hear that, indeed a mismatching font can explain it

Would you mind sending your local font files for the `Decimal` font? :pray:  Obviously I will only use them to investigate the issue, but not having them makes it much harder for me to understand why they're not used properly. Either on Discord or by email at remy@divriots.com

Thanks!

**Comment by muryoh** [comment]
We pushed a couple fixes for both issues, will be fixed in the next release! (soon :crossed_fingers: )
