### ISSUE TITLE
Local storybook + agent - 'Arg mismatch' error

### ISSUE THREAD

**Issue by sebastian-kreft-simployer** [divriots/story-to-design#23]
I built my storybook locally and I tried to import some components by providing `http://localhost:6006/` url. This is what I got:
![image](https://user-images.githubusercontent.com/106516866/194033016-4bb47412-ef42-414f-9d2e-55b875e9b1fa.png)
![image](https://user-images.githubusercontent.com/106516866/194033089-730ff7ed-1a60-474f-ae2f-13c44e8d8ab0.png)
![image](https://user-images.githubusercontent.com/106516866/194033140-70651589-1723-4f8f-8616-854bc04c3dcd.png)

I started the thread on discord here: https://discord.com/channels/744781525119139859/1027131319563591731

---
Bug report identity: Please do not edit

Task path: BwIZ8sIC6SszE38SZFMm/vmpJy7vl2b60VOvuQBU2/bq5orj9xtt7h

**Comment by gqio** [comment]
Hello @sebastian-kreft-simployer 

Thanks for reporting this.
We will try to fix it asap.

**Comment by gqio** [comment]
Hello,

Release has been done with a proper fix inside the Agent.
Could you please reopen if you experience the issue again.

Thanks
