### ISSUE TITLE
Incorrect component tranformation

### ISSUE THREAD

**Issue by sebastian-kreft-simployer** [divriots/story-to-design#24]
I connected my storybook via agent and I try to upload this button:
![image](https://user-images.githubusercontent.com/106516866/194057224-c3247209-be30-424f-b353-c3cb48aec01c.png)

However, after I click "Add to canvas" this is what I see in Figma page:
![image](https://user-images.githubusercontent.com/106516866/194057413-469dcb20-dca3-475a-83c1-ebf3b4400c0d.png)

Also, this makes the ellipsis menu buttons freeze, it's only possible to click in "Add to canvas".

Console log:
![image](https://user-images.githubusercontent.com/106516866/194057834-664d78f3-fbe4-4d82-8a1c-2573fe60df38.png)

---
Bug report identity: Please do not edit

Task path: rqDs4c6aQPgs92W2MrpS/OoRSkW8PQBkdt5Q1JhKf/ivyb97vjhmvb

**Comment by gqio** [comment]
Hello,

New release has been done fixing this issue.
Could you please reopen if you still encounter the issue ?

Thanks
