### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by kylefoundry** [divriots/story-to-design#26]
## Describe the problem ##

Issue with importing variants

---
Bug report identity: Please do not edit

Task path: CHarOlR2ga5SZ89u929s/TN5qLZSWsXMLKGgdU32F/16t8v251nqk08c

**Comment by gqio** [comment]
Hi,

Thanks for reporting this,

As discussed in dm in discord this one should be fixed by now.
Could you please try to report if you encounter another issue ?

Thanks @kylefoundry 
Best
