### ISSUE TITLE
Error while loading components through agent

### ISSUE THREAD

**Issue by sebastian-kreft-simployer** [divriots/story-to-design#27]
## Describe the problem ##
While uploading such component
![image](https://user-images.githubusercontent.com/106516866/196407857-da924dcb-b7c6-48a3-ae97-9b009eee19a9.png)

I get this error
![image](https://user-images.githubusercontent.com/106516866/196407959-72424dc7-e868-438c-8a9d-e4f6752bbb11.png)

I use agent and maybe this log is related:
![image](https://user-images.githubusercontent.com/106516866/196408283-285fe7bb-0cc2-4b99-af4a-44eface0988c.png)

---
Bug report identity: Please do not edit

Task path: BwIZ8sIC6SszE38SZFMm/vmpJy7vl2b60VOvuQBU2/1dh60akxja8d4

**Comment by gqio** [comment]
Hello,

Thanks for reporting this.

I am trying to reproduce and find the error right now

Best

**Comment by gqio** [comment]
Hello again,

After digging into this I think there is an issue with the render. 
Apparently the story is not mounted in your iframe.html

@gluck did you already experience something like this ? Even the storybook api is not present.

**Comment by gqio** [comment]
@muryoh the reproduction report is empty for some assets. Any idea why ?

**Comment by gqio** [comment]
This was due to dev build instead of production build

We will try to provide a better experience with support of dev build
