### ISSUE TITLE
Error while loading components through agent

### ISSUE THREAD

**Issue by sebastian-kreft-simployer** [divriots/story-to-design#28]
## Describe the problem ##
While uploading this component:
![image](https://user-images.githubusercontent.com/106516866/196408692-5c02f81d-bf90-49a3-af86-c91c4c8d92f9.png)

I get this error:
![image](https://user-images.githubusercontent.com/106516866/196408769-492e1397-fb16-485a-99a8-35ea40cfd57b.png)

Agent logs:
![image](https://user-images.githubusercontent.com/106516866/196408997-d901c035-b482-41f7-8e4e-166c9fca97e2.png)

---
Bug report identity: Please do not edit

Task path: BwIZ8sIC6SszE38SZFMm/vmpJy7vl2b60VOvuQBU2/1ywsudb1ryltb4

**Comment by gqio** [comment]
Hello,

Thanks for reporting this.

Did you had issue while reporting this ?
I cannot find the report generated for this one on our side.

Best,

**Comment by sebastian-kreft-simployer** [comment]
Nope, no issue. Should I try again?

**Comment by gqio** [comment]
Yes please 🙏

**Comment by gqio** [comment]
Same as #27
