### ISSUE TITLE
Issue reupload

### ISSUE THREAD

**Issue by sebastian-kreft-simployer** [divriots/story-to-design#29]
## Describe the problem ##
Reupload of this issiue: https://github.com/divriots/story-to-design/issues/28
---
Bug report identity: Please do not edit

Task path: BwIZ8sIC6SszE38SZFMm/vmpJy7vl2b60VOvuQBU2/lde1t0mdvoc9

**Comment by gqio** [comment]
Thanks. 

The report works but it's empty (most likely because of the empty iframe.html)
I will keep you posted when we have a solution for capturing stories within storybook instead of the iframe as a fallback

**Comment by gqio** [comment]
same as #27
