### ISSUE TITLE
Importing

### ISSUE THREAD

**Issue by mariohamann** [divriots/story-to-design#3]
## Describe the problem ##

![CleanShot 2022-08-01 at 21 31 29@2x](https://user-images.githubusercontent.com/26542182/182230511-05e8b80e-cd0b-49b0-bc6a-b00bffbcb6e5.jpg)

When trying to parse a big component with two properties, where one has lots variants (339 x 2) story.to.design gets stucked. I'm trying to get this component since about 16h. :)

The component is an icon component, containing SVGs – maybe that's a problem here?

---
Bug report identity: Please do not edit

Task path: rW72vuvgzd3GZT8EtfP5/NTZkRroV7X5RvIBTlFGh/report-111669j1qiuffi

**Comment by muryoh** [comment]
Fix and released for a few days already :)
Let us know if you still encounter the issue @mariohamann!
