### ISSUE TITLE
Component not loading

### ISSUE THREAD

**Issue by sebastian-kreft-simployer** [divriots/story-to-design#30]
## Describe the problem ##
A component is not loading

I get this error in agent
![image](https://user-images.githubusercontent.com/106516866/196693662-19ff7ee9-53a5-42de-b84e-b2cc44c1df12.png)

---
Bug report identity: Please do not edit

Task path: BwIZ8sIC6SszE38SZFMm/ObeNUaOwuQETCr2pT7fa/l7yr8wbkm7dp

**Comment by gqio** [comment]
Should be fixed by now.

Please tell us if you encounter the same issue.
