### ISSUE TITLE
Can't add additional variants

### ISSUE THREAD

**Issue by sebastian-kreft-simployer** [divriots/story-to-design#31]
## Describe the problem ##
I have a Button component with some variants already added:
![image](https://user-images.githubusercontent.com/106516866/196696708-7797799a-a4ab-4d06-80ab-f16efb1f5c8c.png)

But whenever I try to add any other viariant, e.g. disabled, I get the "variants failed" error, for the newly selected variants.
Logs from agent:
![image](https://user-images.githubusercontent.com/106516866/196697113-eb02a010-408d-4476-9a82-1c244b943279.png)mport { ComponentMeta } from '@storybook/react';

```javascript
import { Button } from './button';

export default {
    title: 'Button',
    component: Button,
} as ComponentMeta<typeof Button>;

export const ForFigma = {
    args: {
        children: 'Button'
    },
    argTypes: {
        disabled: {
            control: 'boolean',
            defaultValue: false
        },
        large: {
            control: 'boolean',
            defaultValue: false
        },
        loading: {
            control: 'boolean',
            defaultValue: false
        },
        color: {
            options: Object.values(Button.Color),
            control: { type: 'select' },
            defaultValue: Button.Color.Primary
        },
    },
};
```

My actual story (args are inferred, but the error occurs even if I type my component with `any`)
![image](https://user-images.githubusercontent.com/106516866/196697844-6289211f-28f6-4a3d-a2bb-5057fe95e7a8.png)

---
Bug report identity: Please do not edit

Task path: BwIZ8sIC6SszE38SZFMm/ObeNUaOwuQETCr2pT7fa/cnh9ke1vsr9ob

**Comment by sebastian-kreft-simployer** [comment]
I was testing the plugin on a dev server, simply by running `start-storybook -p 6006`. It seems that it causes a lot of issues at this moment.
If anybody wants to test this plugin on your local version of storybook, you need to build production files of your storybook and serve them separately, for example:

```bash
npm run build-storybook
npx browser-sync start --server 'storybook-static' --files 'storybook-static' --port 6006
```

With this approach I don't need to release my storybook, and have the "production-like" experience with the plugin ;)

**Comment by gqio** [comment]
Thanks for pointing this a workaround

Dev mode support will solve this issue.

Thanks for the heads up.
