### ISSUE TITLE
`progress` element does not show the progress in Figma

### ISSUE THREAD

**Issue by sebastian-kreft-simployer** [divriots/story-to-design#32]
## Describe the problem ##
This is how my progress bar looks in Storybook:
![image](https://user-images.githubusercontent.com/106516866/197516376-8ef1c449-84e9-4497-8856-fd8b4ffb7009.png)
![image](https://user-images.githubusercontent.com/106516866/197516395-32a5b7f0-13b8-41d2-9e8b-f666ff0e76db.png)

And this is how it renders in Figma (single bar with no progress selected)
![image](https://user-images.githubusercontent.com/106516866/197516543-9616b250-33e5-4a90-848c-a10e218e81b5.png)

---
Bug report identity: Please do not edit

Task path: BwIZ8sIC6SszE38SZFMm/mcCrYUCWKAEIUHHyzkIk/1qh7r3l1xf33fd

**Comment by muryoh** [comment]
Hi @sebastian-kreft-simployer,

Sorry about the late feedback - we have made a few improvements to constraints and borders handling
I unfortunately don't have access to your component for some technical reason but I believe it could be fixed as it a similar component seems to work out ok (similar as in `span`s with `% based widths`)
![image](https://user-images.githubusercontent.com/1789748/208953431-706e29e8-e70b-4448-89bd-65f0b2bee5aa.png)

I'm closing it for now, please feel free to reopen it if needed!

Cheers
Rémy
