### ISSUE TITLE
Components don't have `autolayout` in Figma

### ISSUE THREAD

**Issue by sebastian-kreft-simployer** [divriots/story-to-design#33]
## Describe the problem ##
My components doesn't have autolayout feature anymore. I think it worked a couple of days ago:

![image](https://user-images.githubusercontent.com/106516866/197700289-1fa5fbaa-8ed7-468b-9a3e-ef7c7c3d28a3.png)

---
Bug report identity: Please do not edit

Task path: BwIZ8sIC6SszE38SZFMm/v60py2s7JNZ1NkcbOhjQ/1uprz7xa2r7dg

**Comment by muryoh** [comment]
Hi @sebastian-kreft-simployer !

We just released a few fixes for the existing autolayout, can you check if they fix your issues?
I'll be closing this in the meantime as the report cannot be opened on our side (it was generated with a dev storybook)

Cheers
