### ISSUE TITLE
This button should have autolayout

### ISSUE THREAD

**Issue by georges-gomes** [divriots/story-to-design#35]
## Describe the problem ##

---
Bug report identity: Please do not edit

Task path: aEuLAobbyf8odo85DqKk/FjdiqLGNTOZJ4Xrddcyh/1viubha1qs2bzh

**Comment by muryoh** [comment]
The problem with this one is that we do not handle `width: fit-content` as we do `width: auto`. If the width was auto, it would have worked

There's a difference in behavior which is hard (maybe could be ignored) to translate to Figma

**Comment by georges-gomes** [comment]
For figma I think we `min-content`, `max-content` and `fit-content` could be treated equally with `auto`...

<img width="395" alt="image" src="https://user-images.githubusercontent.com/5250572/201052832-bc34baca-201e-4157-bad7-54f1f410ddf3.png">

There is also `fit-content(<value>)` ... but I think we could treat that equally as a first step.

**Comment by muryoh** [comment]
Should be good since the release yesterday! :pray:
