### ISSUE TITLE
Local Storybook is not syncing with Figma

### ISSUE THREAD

**Issue by SYNchroACK** [divriots/story-to-design#36]
## Describe the problem ##

I except the figma components to be updated based on the changes made in storybook but nothing happens.

**To Reproduce**
1. Run `npm run storybook`
2. Run `./Story-to-design\ Agent serve`
3. Open Figma
4. Run `story.to.design` plugin, provide URL `http://localhost:6006/` (marked as private) and connect to agent
5. Import a button component and add it to canvas
![image](https://user-images.githubusercontent.com/4184292/199268849-042e4b93-cdbb-4c6a-b7dc-2e0a9f0f613c.png)
6. Add button asset to canvas too
![image](https://user-images.githubusercontent.com/4184292/199269394-4cc67f0d-7137-42b1-8f34-615f35c0c268.png)
7. In the storybook code, changed color of the button to something else.
8. Verify that storybook auto-reload with the new color definition
9. Open `story.to.design` plugin again in Figma
![Screenshot from 2022-11-01 15-21-54](https://user-images.githubusercontent.com/4184292/199270286-a016bfa4-991c-431f-b82b-0ec11bee2b08.png)
10. In the end it says that is sync and nothing happens.
![image](https://user-images.githubusercontent.com/4184292/199270805-36c6c29a-ab93-49b9-8459-f41cff2c02cb.png)

---
Bug report identity: Please do not edit

Task path: BwIZ8sIC6SszE38SZFMm/D0NR5bB7JcB1DxADwdEv/1v55sncwd7lks

**Comment by georges-gomes** [comment]
Hi @SYNchroACK,

Thanks for reporting.

Indeed, story.to.design doesn't pickup updates when storybook is in "dev mode".
We already improved the support of "dev mode" and we are working on a solution to detect changes when code is edited live.

Meanwhile, the only workaround is to build your storybook static (`build-storybook`) and serve it with `http-server` for example. Then story.to.design can detect code change. We understand that this is not ideal, that why we are working on "dev mode" updates.

We will report back here when the feature is released.

Thanks!

**Comment by bashmish** [comment]
A small addition from my side: `build-storybook` is not always a silver bullet. If you changed only CSS files, it might not be detected by our version detection algorithm which looks at JS files right now. So if you run into this issue even with `build-storybook`, I recommend updating some JavaScript file in your storybook before building.

But as Georges said, we are going to improve this, stay tuned :)

**Comment by muryoh** [comment]
Hi there, 

Cleaning up issues a bit :)
[Developer mode](https://story.to.design/docs/developer-mode) is available now!
Basically, development storybooks are not meant to be connected to directly, but rather `switched to` with the `developer mode`

Let us know if you have any feedback :hugs: 

Cheers
Rémy
