### ISSUE TITLE
Card import issue

### ISSUE THREAD

**Issue by gqio** [divriots/story-to-design#37]
![image](https://user-images.githubusercontent.com/1063530/200519537-1385ce8c-1887-4a63-902e-7b9f84431c5b.png)

---
Bug report identity: Please do not edit

Task path: JtjG9RHoSghaKWkEcqTF/8vqzG0t79wL9Eq19KFov/1tsfttv1vmkms

**Comment by muryoh** [comment]
From the looks of it this story does not render properly even on the actual storybook
I think it'll need to be fixed there first:
![image](https://user-images.githubusercontent.com/1789748/201048517-e301e7db-d941-4845-944f-32eda2173307.png)

Cheers,
Rémy
