### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by ahvdesign** [divriots/story-to-design#38]
## Describe the problem ##
When importing in this component, the label is missing from the import options, leaving me with an empty frame in Figma. I can provide images upon request!

---
Bug report identity: Please do not edit

Task path: zA8ENQL3zHKPbcxBjUow/Sl02fUuWUkDtRQmyYvfj/14z4w8u1idzj60

**Comment by muryoh** [comment]
Hi @ahvdesign

I confirm this was fixed with [yesterday's release of the agent](https://github.com/divriots/story-to-design/releases/tag/v1.1.5) as I just tried reprocessing your component and they're now featuring the label too :+1: 

Sorry for the inconvenience!

**Comment by ahvdesign** [comment]
Thanks! Can confirm this has been fixed. :)
