### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by iamluisro** [divriots/story-to-design#39]
## Describe the problem ##
Component's children not rendering
---
Bug report identity: Please do not edit

Task path: BwIZ8sIC6SszE38SZFMm/n22TycbvRIwutOGXIYWo/w41yqk1vqkjq0

**Comment by muryoh** [comment]
Hi @iamluisro,
I believe this should be fied with [yesterday's release of the agent](https://github.com/divriots/story-to-design/releases/tag/v1.1.5) which should prompt you to update on the next restart

Do let us know!
Cheers
