### ISSUE TITLE
New component issue report - Importing Icon component fails

### ISSUE THREAD

**Issue by dagfs** [divriots/story-to-design#4]
## Importing Icon Component fails ##

I don't know much more about it than the pluging says it has a error:

![image](https://user-images.githubusercontent.com/26817802/183399304-17487eb7-d201-4543-b006-1b6f1dc3082b.png)

---
Bug report identity: Please do not edit

Task path: bQY4TipQUlXsp7z7MTxa/pdMMo8QHfgXUB4AFjlK0/report-1v74g53z49xk3

**Comment by muryoh** [comment]
Hi @dagfs , sorry to hear that

We'll have a look and keep you updated :pray:

**Comment by bashmish** [comment]
@dagfs I was going to look into it today, but it seems to be non-public now, I get 403 error.
Can you make it public for me to debug, or with basic HTTP auth (you can contact me privately in our [Discord](https://discord.gg/4RBkqjJ) for that, I have the same username there).

**Comment by muryoh** [comment]
The issue was that a few variants could not be loaded as individual canvases because of the way they were implemented inside Storybook
We'll look into improving the way we report this

Thanks for letting us know!
