### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by chogland** [divriots/story-to-design#40]
The text is missing from the buttons when imported.

---
Bug report identity: Please do not edit

Task path: eYrgXQft0ENRI6t2Xg7N/fIh72FVUlD5Oi0WqGntr/1la4ewy54uk3o

**Comment by muryoh** [comment]
Hi there
The issue was only present when using the agent, and should be fixed with [1.1.5 release](https://github.com/divriots/story-to-design/releases/tag/v1.1.5)

Please let us know!
Cheers,
Rémy
