### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by alextsayun** [divriots/story-to-design#44]
## Describe the problem ##

---
Bug report identity: Please do not edit

Task path: 3R3nHaGiGca1AQe9uWyz/qrHUAB6O8Gclk3j832Qp/17ftqladqtwg6

**Comment by muryoh** [comment]
I imagine this one is the same as https://github.com/divriots/story-to-design/issues/43 ?

Will let things settle a bit but might close it later on :)

**Comment by alextsayun** [comment]
yes, it is the same.
