### ISSUE TITLE
Modified component wont update

### ISSUE THREAD

**Issue by audub** [divriots/story-to-design#45]
## Modified component wont update ##

We are testing out story.to.design and imported some simple buttons from our storybook. I changed the color of one of the components afterward and got a message that the components were outdated. But updating the components did not reset the color. I would expect it to. 

---
Bug report identity: Please do not edit

Task path: newfzNPywwjgLvCk11A6/NO3x2OVSMGYbBee90bXj/vu8ubi182uggd

**Comment by gqio** [comment]
Hello @audub 

Are you using the agent ?

If yes are you using the storybook in dev mode ?

Best

**Comment by audub** [comment]
Hi @gqio , 

thank you for the quick answer. We are just using the story.to.design plugin in Figma. No agent. Our storybook is built and hosted on s3, so no dev mode. 

I also tried the re-process option in the plugin without luck.

**Comment by gqio** [comment]
Ok let me have a look

**Comment by gqio** [comment]
Quick question @audub what was the colour before ? and what we should look at ? I got a blue-ish colour here on my side

Did you get the banner where it says that the storybook is out of date ? Did you click on `update version` ?

**Comment by audub** [comment]
@gqio The color in Storybook is blue and always was. And it was imported as blue the first time to Figma. I then changed the imported component in Figma to green. The plugin said components were outdated, but an update did not change the color back to blue in Figma. I was under the impression that it should.

**Comment by gqio** [comment]
> @gqio The color in Storybook is blue and always was. And it was imported as blue the first time to Figma. I then changed the imported component in Figma to green. The plugin said components were outdated, but an update did not change the color back to blue in Figma. I was under the impression that it should.

Hello yes it should have changed if you changed the colour in storybook

But as far as I can see the new storybook you published still contains the the blue one or I am missing something ?
What story or variant should I look ?

**Comment by audub** [comment]
@gqio  Yes, but I never changed the storybook. Just the imported "master" in figma. And lets assume it was by accident and I consider the code the source of truth. How do I "reset" the figma master?

**Comment by gqio** [comment]
Technically story.to.design is parsing the storybook deployed/published.
If the storybook does not changed then the plugin can't be aware of such changes.

If you pushed and merged some changes inside your repository in the code. The plugin expect a new version of the storybook published (containing the changes). Otherwise the plugin can't guess if there are some changes, the only link the plugin has is the url you're entered while connecting to your storybook. It has no connection with the code repository.

Please tell me if it's not clear 🙏 

Aside from that we are closed to release also a dev mode for PRO users when you can just start a local storybook and having the agent pulling updates directly from the local storybook and syncing inside your Figma to have real time updates.

**Comment by gqio** [comment]
Ok we spoke internally and I think I completely missed where you changed the color :) you changed the color in Figma.

And you would like to reset the color according to what is deployed in Storybook ?

Could you please confirm our understanding ?

**Comment by audub** [comment]
@gqio  Thanks for reviewing again. 

Hehe, yes :) Lets imagine a summer intern making changes to the imported master component **in figma**, without knowing better, and we just want to reset to what we have in storybook.

**Comment by gqio** [comment]
> @gqio Thanks for reviewing again.
> 
> Hehe, yes :) Lets imagine a summer intern making changes to the imported master component **in figma**, without knowing better, and we just want to reset to what we have in storybook.

Hello @audub 

We discussed internally about how to do so (since it's not available for now :))
And we will keep you posted when this feature will be available.

Thanks

**Comment by audub** [comment]
No worries, we fixed it by pushing a small adjustment to storybook and reverting afterward.

**Comment by gqio** [comment]
Hello @audub,

In the next version of story.to.design plugin you will be able to `reset` the component to its original version coming from the already parsed storybook story (all override with instance will be kept, but the component will be reset, we try to keep the link between nodes to avoid detached instance)

We will keep you posted once it's released.
Thanks

**Comment by muryoh** [comment]
Released the `Reset` feature a while ago now, sorry, forgot to update the issue :+1:
