### ISSUE TITLE
Cannot download local agent for MacOS - No matching asset for specified platform darwin

### ISSUE THREAD

**Issue by da5idb** [divriots/story-to-design#46]
**Describe the bug**
Cannot download the local agent for MacOS

**To Reproduce**
1. Go to (https://story.to.design/docs/agent)
2. Click on Download for MacOS
3. Goes to https://story.to.design/agent-updates?version=latest&target=darwin
4. See error: No matching asset for specified platform darwin

**Expected behavior**
Agent can be downloaded

**Comment by muryoh** [comment]
Hi @da5idb!

Thanks for letting us know, we'll fix it asap :pray: 
In the meantime you can grab the previous version here: https://github.com/divriots/story-to-design/releases/download/v1.4.0/story-to-design.agent_1.4.0_x64.dmg

Cheers
Rémy

**Comment by muryoh** [comment]
Fixed! Thanks again for the heads-up!
