### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by hrmcdonald** [divriots/story-to-design#47]
Have run into this a few times generating a few components with a large number of variants. Sometimes the progress bar just seems to hang and the processing never finishes so I can never "add to canvas". While it does appear to have stalled again, this time it has now reported "xxxx variants failed".

---
Bug report identity: Please do not edit

Task path: UbQyb2aqMIzumJ4ekiRB/8EvtpLrs9RJNpJmdgDOz/jqu6tpppm2xz

**Comment by muryoh** [comment]
Hi @hrmcdonald ! Sorry to hear that, we'll look into it :+1:

**Comment by muryoh** [comment]
We have a pretty good understanding of where this comes from, we're working on delivering the fix today

**Comment by muryoh** [comment]
We released a fix earlier today, sorry for the late feedback!
