### ISSUE TITLE
Failed import 2/6 variants

### ISSUE THREAD

**Issue by gqio** [divriots/story-to-design#49]
Failed import 2/6 variants

---
Bug report identity: Please do not edit

Task path: VDHa3wgXzblKxeDCyHKM/XoJkO1psbH5UQj9sqEXn/4j56z4141k4nv

**Comment by muryoh** [comment]
That storybook does not like the combination of `filter=undefined` and `isSearchable=true`:

![image](https://user-images.githubusercontent.com/1789748/216308233-f708b1fd-213c-44fc-89ae-2389946815c5.png)

You can still import to canvas, and see what variants are causing the error
