### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by dagfs** [divriots/story-to-design#5]
Importing components worked before restricting access to who has can access our storybook. We have opended for the IP range we were specified the plugin used and have opened it up for port 443.

---
Bug report identity: Please do not edit

Task path: bQY4TipQUlXsp7z7MTxa/9n7rAlMjIBGAPJ64NMXT/report-1oodd9c1nqt4di

**Comment by muryoh** [comment]
Should be fixed, the range was wider than expected!
https://www.gstatic.com/ipranges/cloud.json
