### ISSUE TITLE
New component issue report -  Calendar import not sizing Figma to fit

### ISSUE THREAD

**Issue by russell-beaver-alight** [divriots/story-to-design#51]
## Describe the problem ##
When an update is made in Storybook and then inherited in Figma the frame resizes. 
Is there a way to ensure Size to fit is used for the imported variants or the resizing of the Variant's frame does not happen with each new Storybook update? 

This is how it imports. 
<img width="556" alt="image" src="https://user-images.githubusercontent.com/116389280/221940367-6b5ce74d-c470-48e5-9db0-9155a370aa81.png">

This is when Size to fit is used. 
<img width="808" alt="image" src="https://user-images.githubusercontent.com/116389280/221940598-026692de-e432-44cf-8e74-60ecbf6a4cf6.png">

---
Bug report identity: Please do not edit

Task path: nP4IFFp6FCExjMVypDHh/Gu938h1LnxZdxiPhRkjr/1pluefb1f8ine5

**Comment by muryoh** [comment]
Hello!

I'll be looking into it - it is indeed not expected to have to resize manually the frames so that the component itself is visible

It's happening because the element containing the calendar is of size 0, which is why we create that empty frame that contains the calendar

Will try to fix!

**Comment by muryoh** [comment]
We released a patch yesterday that should fix this 
You will need to do a "reprocess" (in the dropdown menu of the component) to benefit from the fix for already processed variants

Hope it fixes it, don't hesitate to reopen if needed

Cheers
Rémy

**Comment by russell-beaver-alight** [comment]
Remy,
This is great news.
Thank you for helping us sort this out!
–Russell

From: Remy ***@***.***>
Date: Thursday, March 2, 2023 at 3:42 PM
To: divriots/story-to-design ***@***.***>
Cc: Russell Beaver ***@***.***>, Author ***@***.***>
Subject: Re: [divriots/story-to-design] New component issue report - Calendar import not sizing Figma to fit (Issue #51)
[External]

Closed #51<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdivriots%2Fstory-to-design%2Fissues%2F51&data=05%7C01%7Crussell.beaver%40alight.com%7C56fadd1b12424a0a319408db1b66f575%7C232a81501ff64e00ad51c491fb66cb74%7C1%7C0%7C638133901240298183%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TORqJ%2Bzc3RmJyaZP1NAyZwDzC2eFqvxlJQzkNrbfmho%3D&reserved=0> as completed.
