### ISSUE TITLE
Right-padding on exported components (with additional wrappers)

### ISSUE THREAD

**Issue by VoloDziuKoho** [divriots/story-to-design#53]
## Describe the problem ##

Similar to the previously posted issue, but with additional wrappers around the component. When wrappers are removed, the problem is gone, but this suggests to me that the solution is not working in all cases

---
Bug report identity: Please do not edit

Task path: Dlispy0XNKMa6bQDHNHV/UAvYNn88jBPnFQPNL6tG/1f2921b1wts7zo

**Comment by muryoh** [comment]
Hello!

One of the child elements of the root element has a width of 100%, in which case we're not "zooming in" further to adapt to child elements

We do it when the size is auto/fit-content/etc, ie widths that explicit "sizing depending on children". Doing it here would possibly mean the user wanted it to be full width and have a space but we trimmed it not considering it

There are a couple possibilities:
- review the width 100% (if memory serves it was on the `error` element)
- use a custom selector to tell story.to.design the element you want to capture is actually a child of that element

Of course we could still revisit our logic if it makes sense to do so, don't hesitate to let us know

Cheers!
Rémy
