### ISSUE TITLE
Re-process component is stuck

### ISSUE THREAD

**Issue by okonet** [divriots/story-to-design#57]
## Describe the problem ##

After pulling a new version of storybook with the updated `s2d` definitions, the re-processing is stuck for tens of minutes.

---
Bug report identity: Please do not edit

Task path: 58YZgFPDLBpobrpjG2b4/cRhp7J1rumCLYGXR2AzF/1cajdsprfbzv6

**Comment by muryoh** [comment]
Hi there, sorry to hear that!

Do you have more details about what happened exactly? Did it eventually finish, was it just stuck at reprocessing without progressing at all?

Cheers
Remy

**Comment by muryoh** [comment]
Is it a duplicate of https://github.com/divriots/story-to-design/issues/58 by any chance?

**Comment by okonet** [comment]
I created a new storybook integration so I’m not sure what was causing it. I’d say let’s close for now.
