### ISSUE TITLE
Infinite "Loading stories" after storybook update

### ISSUE THREAD

**Issue by okonet** [divriots/story-to-design#58]
**Describe the bug**

After clicking "Update" for a new version of a storybook, I see an infinite loading spinner for "Loading stories". The plugin window is unresponsive and none of other buttons are clickable so I cannot open logs or update to another version of the storybook.

**To Reproduce**
1. Update storybook
2. Click on 'Update'

**Expected behavior**

It should finish loading stories eventually and unblock the UI.

**Screenshots**

https://user-images.githubusercontent.com/11071/231755729-7e3b03a6-32a8-466f-9e9d-234c1c8b21fb.mp4

## Update

After opening the console, I see this error:

```
Uncaught Error: Arg has no options: children
    at NA (<anonymous>:1:526554)
    at <anonymous>:1:527083
    at Array.map (<anonymous>)
    at ND (<anonymous>:1:527077)
    at NF (<anonymous>:1:527277)
    at NQ (<anonymous>:1:528953)
    at a0S (<anonymous>:1:598985)
    at <anonymous>:1:600758
    at Array.map (<anonymous>)
    at <anonymous>:1:600752
```

which seem to happen due to this definition of the `s2d` parameters in the story:

```
export const Figma = {
  parameters: {
    s2d: {
      initArgs: {
        ':selector': badgeRoot,
      },
      variantProperties: [
        'tone',
        'size',
        'shade',
        {
          name: 'Label',
          fromArg: 'children',
        },
      ],
    },
  },
  args: {
    children: 'Badge',
  },
} satisfies Story;
```

I've since removed the `s2d` completely from the updated storybook but since the UI blocks any clicks, I cannot update it anymore.

**Comment by muryoh** [comment]
Hi @okonet ,

Do you have any error in the console?

Cheers.
Remy

**Comment by muryoh** [comment]
Ah I see you've updated the description since I asked

Yes, there currently is a problem when a story arg that was imported is removed
We have a fix for it which we'll release soon

**Comment by okonet** [comment]
Digging deeper: it seems that the runtime error occurs any time I click on *any of the buttons* on screen:


https://user-images.githubusercontent.com/11071/231757815-173b0838-805e-4f74-834c-ba7308c28d3d.mp4

**Comment by muryoh** [comment]
Hey again, we just released the fix
As usual with Figma - to load the updated plugin, you'll need to refresh the tab Figma was loaded in (true for both Figma in browser and the app)

Cheers!

**Comment by okonet** [comment]
Perfect! Thanks a lot
