### ISSUE TITLE
Keeps seeing "Review and update"

### ISSUE THREAD

**Issue by okonet** [divriots/story-to-design#59]
## Describe the problem ##

After updating the advanced config of the Button component, it didn't actually update it and keeps showing the "Review and update" button.

Also, the "Reset canvas" is disabled for some reason.

<img width="444" alt="CleanShot 2023-04-13 at 16 08 55@2x" src="https://user-images.githubusercontent.com/11071/231785556-2a76f102-a200-409b-9439-6afe0c372f78.png">

---
Bug report identity: Please do not edit

Task path: A180IkCIjkpoihHcop0Y/6ipQ3AOasCHC90nRF9Yt/1mnj8002e4h1h

**Comment by muryoh** [comment]
Hi,

Do you have any error in the console when clicking `Review and update`? I cannot seem to reproduce on my end

Cheers,
Remy

**Comment by okonet** [comment]
@muryoh not really. I just restarted and that's what I see in the logs:

```
[4/17/2023, 9:13:15 AM] Startup
[4/17/2023, 9:13:15 AM] Ignoring fontName with empty key
```

**Comment by muryoh** [comment]
Do you by any chance know what you changed in the advanced config? I don't remember seeing such a problem before

**Comment by okonet** [comment]
I have this in the advanced config for this component:

```
{
  "initArgs": {},
  "variantProperties": [
    "size",
    {
      "name": "icon",
      "values": [
        {
          "name": "without"
        },
        {
          "name": "leading",
          "$story": "buttons-base-button--leading-icon"
        }
      ]
    }
  ]
}
```

**Comment by muryoh** [comment]
Reproduced, on it 👍

**Comment by muryoh** [comment]
So the problem is that this configuration does not do what you think it does
I believe you wanted to use
```
{
  "initArgs": {},
  "variantProperties": [
    "size",
    {
      "name": "icon",
      "values": [
        {
          "name": "without"
        },
        {
          "name": "leading",
          "withArgs": {
            ":story": "buttons-base-button--leading-icon"
          }
        }
      ]
    }
  ]
}
```

This one does work
The other one does something unexpected as the `$story` field is actually not used this way, ending up in 6 variants where we actually only have 3 different components. I'll add a fix for the never ending `Review and update` workflow to avoid this

We'll also consider improving the linting on the configuration to avoid being able to specify a config like this which won't work

**Comment by muryoh** [comment]
The fix for the update loop has been pushed, we'll look into improving the linting 🙏
