### ISSUE TITLE
withArgs inheritance issues (maybe not?)

### ISSUE THREAD

**Issue by okonet** [divriots/story-to-design#60]
## Describe the problem ##

I'm using this advanced config:

```
{
  "initArgs": {},
  "variantProperties": [
    {
      "name": "icon",
      "values": [
        {
          "name": "without",
          "withArgs": {
            "name": "test",
            "value": "No icon"
          }
        },
        {
          "name": "start",
          "withArgs": {
            "name": "test",
            "value": "With icon"
          }
        }
      ]
    }
  ]
}
```

and both variants render with the same label text inside the Input.

If I set the `label` in the `initArgs`, both variants render it regardless of their `withArgs`.

---
Bug report identity: Please do not edit

Task path: A180IkCIjkpoihHcop0Y/6ipQ3AOasCHC90nRF9Yt/zg5wnd16hxqq7

**Comment by okonet** [comment]
Additionally, it looks like it's not passing the right one when used with the `:story` either:

![CleanShot 2023-04-13 at 16 21 12@2x](https://user-images.githubusercontent.com/11071/231789054-f1d28d94-a2e0-45f2-8c02-7a1b2823cc8a.png)

Disregard the "start" one since it doesn't pass `args` in the story itself.

**Comment by okonet** [comment]
Is this happening because the `value` being mapped to a component property in Figma?

**Comment by georges-gomes** [comment]
Fixed in latest version 👍  Talking to `okonet` on discord
