### ISSUE TITLE
Nested sub-component doesn't work

### ISSUE THREAD

**Issue by okonet** [divriots/story-to-design#61]
## Describe the problem ##

Previously, the Icon component that rendered inside the Input was referencing to the proper Figma component. Now it's not anymore.

---
Bug report identity: Please do not edit

Task path: A180IkCIjkpoihHcop0Y/EQKzvhi6cT82Fwvpk2fN/1u559iv99y8yy

**Comment by muryoh** [comment]
Hi there,

Sorry to hear that!
It seems to be working on my end - would you mind sharing what you imported on the canvas?
Something to consider/check: at the moment, import order on the canvas matters. ie if you import the input first, then the icons, the input component on the canvas is not updated to backreference the icons. If this is what you did however, then you could use the `Reset canvas` option on the input component to retrigger subcomponents detection for the input component

Don't hesitate to ping me on [discord](https://story.to.design/chat) (Remy#5067) if you'd rather speak more directly

Cheers
Remy

**Comment by georges-gomes** [comment]
We found that the "Review and update" process was discarding sub-components. 
Fix ongoing.

**Comment by okonet** [comment]
I can confirm with the latest version they are now recognized as sub-components again.
