### ISSUE TITLE
Autolayout not applied

### ISSUE THREAD

**Issue by okonet** [divriots/story-to-design#62]
My component uses flex box, but the imported component doesn't have auto-layout applied.

<img width="901" alt="CleanShot 2023-04-18 at 09 56 47@2x" src="https://user-images.githubusercontent.com/11071/232710709-8f7d5e8d-c340-4faa-828c-63e62c52588a.png">

<img width="1404" alt="CleanShot 2023-04-18 at 09 57 01@2x" src="https://user-images.githubusercontent.com/11071/232710759-4e839e45-e634-4f8b-95b8-adaa3ab094f1.png">

---
Bug report identity: Please do not edit

Task path: A180IkCIjkpoihHcop0Y/EQKzvhi6cT82Fwvpk2fN/133d72odgmkvb

**Comment by muryoh** [comment]
Hi there,

Just making sure, but in your case it seems like what you want is better constraints on the children, not autolayout, right?
I feel like you are resizing the component itself, in which case autolayout won't help

My understanding is something along those lines
- if resizing the component, then you want constraints on the children to "stick" to the changes on the parent
- if rezising the children (like text withing a button) is expected to impact the component, then autolayout is needed

Cheers
Remy

**Comment by okonet** [comment]
I'm not sure I get this:

I use the flex box to layout children like this: `[[startSlot][-----children-----][endSlot]]` so the wrapper container has `display: flex`, and `children` container has `flexGrow: 1` applied. So the `startSlot` and `endSlot` are always on the edges and the content area is constrained by the component width.

When importing to Figma I would expect a similar configuration achieved with the auto-layout:

<img width="459" alt="CleanShot 2023-05-12 at 12 58 33@2x" src="https://github.com/divriots/story-to-design/assets/11071/d60c870c-4577-46c7-b051-6c9fb0439280">

https://www.figma.com/file/33LBeIqygqHnPNrJFB2Uhp/Untitled?type=design&node-id=1%3A3&t=bJT4glHNvZEFuqBC-1

So that when I use this instance I can do this:


https://github.com/divriots/story-to-design/assets/11071/99ecb0d4-0f2a-48a1-a110-63056caebd19

which is the same what the `flexGrow: 1` will give me in the browser.

Constraints on the children sound to me as a translation to `position: absolute`.

**Comment by muryoh** [comment]
Oh you're completely right, my bad
Will see what can be done 👍

**Comment by gqio** [comment]
Hello,

We released lately the v2 of autolayout,
Could you please check if it's still the case ?
Please reopen if needed

Best.
