### ISSUE TITLE
Sub-components doesn't create instance swap properties

### ISSUE THREAD

**Issue by okonet** [divriots/story-to-design#63]
I'm not sure if that's expected or not, but I would expect an sub-component resulting in an instance swap property in Figma.

Currently, I still would need to do this manually.

---
Bug report identity: Please do not edit

Task path: A180IkCIjkpoihHcop0Y/EQKzvhi6cT82Fwvpk2fN/14zrnzre7vrbx

**Comment by muryoh** [comment]
Hi @okonet , sorry for not coming back to you earlier about this

We don't have that feature yet - but we can of course consider adding it!
Would you mind detailing a bit the workflow you're expecting to work here?

I'm not entirely sure why you want them - my understanding with swap properties is that they somehow better replace the variants in some case. For example if you have 300 icons as components and create a button component with icon as a variant, then you'll need 300 variants, one for each icon. While with instance swap properties you'd only have 1 button variant in which you would be able to swap the icon instance. Is this the workflow you want to achieve?

Cheers,
Remy

**Comment by okonet** [comment]
I think we mean the same thing. It's just currently if I have a sub-component it doesn't being added to the component props as an Instance swap. Does this make sense?

**Comment by muryoh** [comment]
Oh you're completely right, my bad
Will see what can be done 👍

**Comment by muryoh** [comment]
It does

I've looked into it and unfortunately I believe the Figma API does not allow this yet. It can be done manually (https://help.figma.com/hc/en-us/articles/5579474826519-Explore-component-properties#exposed-instances) but not with the API. I've submitted a request to Figma to confirm and ask them for any ETA

In the meantime, you still have the possibility to change the subcomponent property directly by diving into it

Cheers

**Comment by muryoh** [comment]
Hey, coming back on the issue
Actually found a way to do it with the current API - it will be available with the next release and will basically consist of exposing nested instances as mentioned just before

It will result in something like this

https://github.com/divriots/story-to-design/assets/1789748/506a2480-2a47-43c7-ac05-c45fd3a96a01


Cheers
Remy

**Comment by gqio** [comment]
Fixed
