### ISSUE TITLE
Sub-component were removed on re-processing

### ISSUE THREAD

**Issue by okonet** [divriots/story-to-design#64]
After changing the variantProperties (added `initArgs.value`) all previously mapped sub-components were removed:

<img width="223" alt="CleanShot 2023-04-18 at 10 19 19@2x" src="https://user-images.githubusercontent.com/11071/232716768-eda1f843-ce34-440b-8096-265b3ec122a7.png">

---
Bug report identity: Please do not edit

Task path: A180IkCIjkpoihHcop0Y/EQKzvhi6cT82Fwvpk2fN/1gcjosj10jabqq

**Comment by muryoh** [comment]
Hi @okonet , I believe this was fixed in the previous released (reprocesses/updates were not mapping subcomponents)

I'll therefore be closing the issue - do feel free to reopen it if it needs further investigation

Cheers,
Remy

**Comment by muryoh** [comment]
fyi I did notice a problem with the fix we did for that one, as the components that we're updating are being used as subcomponents themselves.

Fix is in progress on our side
