### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by sgbelim** [divriots/story-to-design#66]
## Describe the problem ##

---
Bug report identity: Please do not edit

Task path: BVqhTN9j865biNqgL8NO/nxd5x7AQMOsum7ui753s/138dsed1v7rtz2

**Comment by muryoh** [comment]
Hi @sgbelim, would you mind describing the issue you're seeing so we can make sure to look into what your problem is?

Cheers,
Remy

**Comment by gqio** [comment]
Hello,

Are you still experiencing the issue ?
Please reopen if needed

Best.
