### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by KlausGotti** [divriots/story-to-design#67]
## Describe the problem ##

After installation of the newest release (1.16.0) following the procedure the import of a new component fails. I did a logout, login and restart, too.

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/L3Pblwb3aezW4N1GGNtk/1mzgzfr63eoz0

**Comment by gluck** [comment]
Fixed in 1.16.1, sorry
