### ISSUE TITLE
[Bug] Import new component

### ISSUE THREAD

**Issue by elenabraeutigam** [divriots/story-to-design#68]
## Describe the problem ##

Since v1.16.0, whenever I try to import a new component, I receive the following error:

<img width="435" alt="Screenshot 2023-04-18 at 17 04 24" src="https://user-images.githubusercontent.com/129752452/233021611-a86d9b44-e545-4dce-b04c-54f0555f8035.png">

I tried restarting and logging out and in to Figma and story.to.design, but that did not fix the issue.
Now, even the already imported components show the same error message.

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/SSoYdtGjBBUkjpKIR9zH/1omndn9474au6

**Comment by gluck** [comment]
Fixed in 1.16.1, sorry about the hiccup.
