### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by sslPentia** [divriots/story-to-design#69]
## Describe the problem ##

---
Bug report identity: Please do not edit

Task path: 5SKyZds5XqqFF7zC08If/AID8N9vMX9ykcbF5nMoN/fo1h1m1t0vr4f

**Comment by muryoh** [comment]
Hi there, can you describe the issue you're having?

Cheers
Rémy

**Comment by sslPentia** [comment]
Hi Rémy,

I found the error on my end. I’m sorry for your trouble, you can go ahead close the issue.

Cheers

Sebastian Søgaard Larsen
Frontend Consultant @ Pentia, +45 4221 1006
