### ISSUE TITLE
Absolutely positioned tooltip arrow being omitted from converted story

### ISSUE THREAD

**Issue by Aaron-Pool** [divriots/story-to-design#72]
## Describe the problem ##

A tooltip arrow is not being included in the story content.

What is being captured:
![image](https://github.com/divriots/story-to-design/assets/5634834/3fdfca6b-33a2-4707-91dd-d4d389de7646)

What should be captured:
![image](https://github.com/divriots/story-to-design/assets/5634834/16f984f1-62e7-4e4e-8bff-9e9cca919644)

---
Bug report identity: Please do not edit

Task path: Jis8deOzbqwSsSIUE8VN/NOJmB1UGG0t2DW1e5JMr/136tn7gfeyk70

**Comment by gluck** [comment]
Hi @Aaron-Pool , thanks for reporting the issue, we were mistakenly ignoring children of `visibility: hidden` elements, whereas they can be visible if you set `visibility: visible` on them (which is the case for the `:before` child arrow on your story).
Fix is done, will be shipped in next update, stay tuned:

![image](https://github.com/divriots/story-to-design/assets/604263/91005dee-2a58-44a8-8767-324145235401)

**Comment by Aaron-Pool** [comment]
Thanks @gluck 🚀

**Comment by gluck** [comment]
The agent has been released, if you upgrade to `1.18.17` you should get the arrow as expected.
Cheers.
