### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by CaptainYarb** [divriots/story-to-design#75]
Fails to import any of our variants. This is the most rudimentary one worth consideration. Is this related to the Cloudflare service tokens?

---
Bug report identity: Please do not edit

Task path: 3K1HWreYPmpnwBbOZrUd/YheCDwzN6ryoANlkOCm5/1liezu31azprc9

**Comment by gqio** [comment]
Hello,

Fix is being deployed.
Should be available in less than 30 min.
Please reopen if needed

Thanks for reporting it

Best.
