### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by nils-rohe** [divriots/story-to-design#76]
In storybook everything looks fine - the number in the first bubble is white (it's a 1 in a blue-ish bubble).. but after import the 1 has the same blue-ish color.. the numbers are also not centered anymore in the bubble. Since everything is correct in the storybook story it seems to be a problem with the story.to.desigm import. 

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/klLzmWPddgA4gbrgZFFw/w0t6v03s31fm

**Comment by gqio** [comment]
Hello,

Fix is being deployed.
Should be available in less than 30 min.
Please reopen if needed

Thanks for reporting it

Best.
