### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by nils-rohe** [divriots/story-to-design#77]
This is a duplicate of https://github.com/divriots/story-to-design/issues/76 but this time reported in non-dev mode.

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/muRGQf71D35XMfT4tac9/1cwwxghz0z2c2

**Comment by gqio** [comment]
Hello,

Fix is being deployed.
Should be available in less than 30 min.
Please reopen if needed

Thanks for reporting it

Best.
