### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by CaptainYarb** [divriots/story-to-design#78]
Expected layout from Storybook:

![Storybook](https://github.com/divriots/story-to-design/assets/93261/ed6865d8-bb46-4e2d-9f13-da6ab856276d)

Figma Layout:

![Figma](https://github.com/divriots/story-to-design/assets/93261/a4c6caf9-f40a-4d99-b75f-fbdf99254a44)

The width of the label seems to be squished. Also the icon has a white background rather than transparent.

---
Bug report identity: Please do not edit

Task path: 3K1HWreYPmpnwBbOZrUd/MZZj9BYUFszJXwZLFuzU/154u8of5zfpur

**Comment by gqio** [comment]
Hello @CaptainYarb 

Normally the issue with field spacing should be fixed with the last version of the plugin.
For the Icon with the white background it's another issue coming from subcomponent mapping.

@georges-gomes is on the second part of this issue.

Best

**Comment by gqio** [comment]
Hello @CaptainYarb 

![image](https://github.com/divriots/story-to-design/assets/1063530/d207787e-16f6-4cf6-acdc-1ff6e393426c)

Fix has been merged.
Release should follow today 🤞 

Thanks again for reporting it
Best
