### ISSUE TITLE
Storybook version is no longer live, check updates

### ISSUE THREAD

**Issue by dagfs** [divriots/story-to-design#8]
##Storybook version is no longer live, check updates ##

We get the console error `Storybook version is no longer live, check updates` and the component stops being processes(the process bar stops). 

We managed to import quite a few components, but not everyone. We now get this error within that one file whenever we try to import more components. Creating a new Figma file and starting to import works.

![image](https://user-images.githubusercontent.com/26817802/185338874-20f05529-cc7c-4458-a87b-db3ffb553be0.png)

---
Bug report identity: Please do not edit

Task path: bQY4TipQUlXsp7z7MTxa/5BadOqvGZA3RykYgW1xV/report-fb9bw516ztx4u

**Comment by muryoh** [comment]
This error occurs specifically when the storybook was updated
At the moment the "switching to a new version of my storybook" is still manual and needs to be done through the `Reset` option (and in that case all imported components need to be `Re-processed`)

We are working hard on releasing a more straightforward process in that case. Should be available in a couple weeks at most!
