### ISSUE TITLE
Textfield label: positioning is off, label is cutoff (2)

### ISSUE THREAD

**Issue by nils-rohe** [divriots/story-to-design#80]
Same as [this](https://github.com/divriots/story-to-design/issues/79) - reporting this again because support couldn't import the component (see [here](https://discord.com/channels/744781525119139859/1025067953982541854))

![image](https://github.com/divriots/story-to-design/assets/108518250/783d6b97-b5d2-4745-8c2b-db0fa386d618)

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/muRGQf71D35XMfT4tac9/180o8c2fcx06q

**Comment by gqio** [comment]
Hi, 

@nils-rohe a fix has been deployed.
if it's not enough just please reopen this ticket.

Thanks a lot for your patience.
Happy designing
