### ISSUE TITLE
material-ui/IconButton missing padding in default state

### ISSUE THREAD

**Issue by alexandergrot** [divriots/story-to-design#82]
we use material ui and in this case it's only this component https://mui.com/material-ui/react-button/#icon-button which is used in the story.

when importing this story, it seems like the IconButton is missing its padding in the default state. if the hover state is activated, the padding is added, which changes the size of the whole component compared to the default state.

to make it more clear here are screenshots comparing the 2 states in storybook and the imported story in figma:

default state storybook: 
![grafik](https://github.com/divriots/story-to-design/assets/102791744/23f4e7a1-b43e-432f-8126-ad5466f08dbb)
hover state in storybook:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/576aaef2-ac54-469c-a63d-10f4a1a39f50)

corresponding states in figma:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/fb65d8b5-baa0-4166-8bf0-8ccaaf332e39)

and just for the record if you use those states:
default state:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/43c5b18f-88f0-40d7-a587-c10fe4378703)
hover state:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/3ab10b77-fe5d-4d20-a914-9f5fe43b6ca2)

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/hrwazxzLAVxmddJaf3sn/xihko52ipylt

**Comment by alexandergrot** [comment]
very similar behaviour can be seen for [materlai-ui/Checkbox](https://mui.com/material-ui/react-checkbox/) (active/hover state), [material-ui/Radio](https://mui.com/material-ui/react-radio-button/) (disabled state) and [material-ui/Select](https://mui.com/material-ui/react-select/) (active/tap state).

should i open new issues for those or wait until this one is resolved and see if it fixes those as well?

**Comment by muryoh** [comment]
> very similar behaviour can be seen for [materlai-ui/Checkbox](https://mui.com/material-ui/react-checkbox/) (active/hover state), [material-ui/Radio](https://mui.com/material-ui/react-radio-button/) (disabled state) and [material-ui/Select](https://mui.com/material-ui/react-select/) (active/tap state).
> 
> should i open new issues for those or wait until this one is resolved and see if it fixes those as well?

They may be related!
But feel free to open another one for us to check so you can avoid waiting too long
