### ISSUE TITLE
Rendering Issue with "Reset Canvas" option

### ISSUE THREAD

**Issue by elenabraeutigam** [divriots/story-to-design#83]
I currently often run into the issue that when a component was updated in Storybook and I review and update it in the plugin, the rendering in the Figma canvas is slightly off (even though the preview in the plugin when reviewing the updates is correct). Clicking on "Reset Canvas" currently ends up damaging the rendering even more (see image). Reprocessing the Story does not change anything at all. Only when I delete the Figma canvas and then click "Add to Canvas" in the plugin again, it is rendered correctly. But being forced to delete the Figma canvas would then cause issues with child components (in different Figma files) not being synced to that component anymore.

<img width="642" alt="Screenshot 2023-07-24 at 14 57 49" src="https://github.com/divriots/story-to-design/assets/129752452/5750edea-ce2b-40ed-a02d-7da43703f655">

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/UvsMk8HRvIcV9G0dnjQe/909xba1obuus7

**Comment by gqio** [comment]
Hello @elenabraeutigam 

It should be fixed with the latest release of the plugin.
Please tell me if the problem persist

Best.

**Comment by elenabraeutigam** [comment]
I tested the Reset Canvas on a bunch of components and for some it seems to be fine, but other times, this Option still seems to damage the component slightly. 

Here is an example of our checkbox component:
When I click "Reset Canvas", the text of this component repositions slightly further up.
<img width="909" alt="ResetCanvas" src="https://github.com/divriots/story-to-design/assets/129752452/7e87f571-06e0-4fb8-95db-8d3e663d7db0">

When deleting the Canvas in Figma and then pressing "Add to Canvas" in the plugin again, the new canvas looks correct again:
<img width="915" alt="AddToCanvas" src="https://github.com/divriots/story-to-design/assets/129752452/df181bc1-7f3f-4764-a2e0-c312f0b4a9dc">

**Comment by elenabraeutigam** [comment]
I do have to mention though that when starting the agent, I was not asked whether I wanted to update to the newest version. I currently have the Version: 1.18.46.
Is this correct?

**Comment by gqio** [comment]
Yes we missed some fixes in the latest release 🤦 
Should be fine @elenabraeutigam
