### ISSUE TITLE
Additional blank space to left of component

### ISSUE THREAD

**Issue by nils-rohe** [divriots/story-to-design#85]
This component has a lot of blank space towards the left:
![image](https://github.com/divriots/story-to-design/assets/108518250/69e6a353-9ef9-4634-b197-303f77829a82)

This is not the case in storybook though. Seems something pushes everything to the right when imported to Figma. 

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/dsOju8GEbqSFBPM87gPa/1qb6dr4s2llwl

**Comment by muryoh** [comment]
Hi @nils-rohe , sorry about that!

It will be fixed in the next release - we had a problem when computing component sizes

Cheers
Remy

**Comment by gqio** [comment]
Should be released by now

Thanks again for reporting it
