### ISSUE TITLE
Inner container doesn't shrink with outer one

### ISSUE THREAD

**Issue by alexandergrot** [divriots/story-to-design#87]
hey all,

we have an `AppBar` story which is close to examples in [material-ui/AppBar](https://mui.com/material-ui/react-app-bar/)

when importing and resizing the component in figma, the inner container seems to not shring accordingly, causing the right icon to disappear:

default state after importing:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/9980848b-5390-4ee8-a54d-238bf61c8379)

resizing the outer container with inner container highlighted:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/d962d1b2-649d-422e-9e30-dc98e6e158c3)

expected behaviour would be that the icon keeps the same distance to the right end of the container and the inner container shrinks accordingly.

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/MqMtAjToG0l8Uxna4ZNc/1l3upx51645tj9

**Comment by muryoh** [comment]
Hi there,

Oops, sorry to hear that
We're struggling on the flex-grow child there, as its height is 0 so it currently is messing up our autolayout algorithm

![image](https://github.com/divriots/story-to-design/assets/1789748/f2b1c4fb-d866-4ae2-aea0-64f28bd9cfa4)

Will have a look!

**Comment by muryoh** [comment]
Pushed a change for the team to review, since it's summer time it might take a bit more than usual

In the meantime here's a sneak peek so you can confirm this is the expected behavior (I also played with the min height of a child there to check the parent resizes as expected)

https://github.com/divriots/story-to-design/assets/1789748/e6c49cec-932f-4fa6-9ec3-30b9eac2a65d

**Comment by alexandergrot** [comment]
hey @muryoh, sorry for the late answer. looks good to me :) thanks!

**Comment by muryoh** [comment]
We released a patch earlier today which should contain the fix!
