### ISSUE TITLE
container doesnt resize with length of text (material-ui/Chip)

### ISSUE THREAD

**Issue by alexandergrot** [divriots/story-to-design#89]
hey all,

imported a story with simple styles for [material-ui/chip](https://mui.com/material-ui/react-chip/). in the storybook you can assign a label for this chip, which renders just fine. in the imported story however, the container doesnt grow when adding some long text as label.

example screenshots:

storybook:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/f9bcee80-dfba-466c-af8a-417a15242d1a)

figma imported story:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/4d4d671a-4dab-4ad2-bcae-51453d15315b)

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/OgkUhxSLu1SehmKari3V/1u65qf9mg6lc6

**Comment by gluck** [comment]
Hi @alexandergrot, thanks for reporting.
The issue was found, the text wasn't positioned correctly, and prevented to apply autolayout.
Will keep you updated when it's released, you'll then have to use "reset canvas" on the component to re-paint it with proper autolayout settings.

**Comment by muryoh** [comment]
Hi there! We just released a new version of story.to.design which includes the fix for this one
Don't hesitate to re-open if needed :+1:
