### ISSUE TITLE
materlal-ui/Stepper: text grows in wrong direction; content text fixed width

### ISSUE THREAD

**Issue by alexandergrot** [divriots/story-to-design#90]
hey all, 
we have a problem with this component, it seems like the title for the selected step in the vertical variant of the [material-ui/Stepper](https://mui.com/material-ui/react-stepper/#vertical-stepper) grows in the wrong direction, it should grow to the right but grows in both direction. also the content of the current selected step has a fixed width, so when adding longer text it grows only vertically.

storybook:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/a6fb08a3-e8b6-4ed4-a8bf-8b8387a6abe8)

imported story to figma:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/b526a698-268f-4df0-9ae0-9ed871aa79ed)

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/OgkUhxSLu1SehmKari3V/14136bqris6g8

**Comment by nils-rohe** [comment]
Hi @gluck , I saw that you assigned yourself here. Just wanted to follow up since it has been a while since Aug 4. Thanks!

**Comment by gqio** [comment]
Hello @nils-rohe 

We still have issues with this (see the padding-box of the button is outside of the border-box of the story)

![image](https://github.com/divriots/story-to-design/assets/1063530/95251864-27b1-41ba-b573-aea785d86694)

Not sure how to represent this in figma with autolayout since there is not margin concept in figma and negative padding are not accepted in Figma

**Comment by gqio** [comment]
Hello @alexandergrot 

Wow this one was really really tricky and implied a lot of change in our autolayout algo.
But it helped to solve a lot of issues on our side

Thanks a lot for reporting this.
Sorry for the delay but the impact was huge for us.

Normally every issues have been solved.
Don't hesitate to drop us a message or rereport if it's not the case.

Best.
