### ISSUE TITLE
Iframe import is incorrect size on variants

### ISSUE THREAD

**Issue by chungsi** [divriots/story-to-design#93]
## Describe the problem ##

We have a component that renders a background video through an iframe, and it has multiple size variants. The first size variant seems to import fine (an image preview behind the banner text), but subsequent size variants import strangely (see screenshot of side-by-side). 
Is this an issue with using an iframe? Because if so, I'm thinking we could have a static version in Storybook so importing can just use that version and not the video one.

![image](https://github.com/divriots/story-to-design/assets/14225300/18f5e5e9-76e9-443d-9079-0d2548a19c5f)

---
Bug report identity: Please do not edit

Task path: R702fkgNoAQvwSdKueSF/tOibszywZThBMr4v1chn/c93iit1ggr49m

**Comment by muryoh** [comment]
Hi there

Having a look
First problem I see is that the vimeo player does not load in Chromium :(
Checking what's happening with the black background (I can see that iframe has huge dimensions, probably related, but that's still not expected)

EDIT: I can see you do get the picture, so maybe the vimeo player thing is specific to chromium on apple silicon 🤔

**Comment by muryoh** [comment]
The (sizing/clipping) problem is caused by a behavior we want for html.to.design, but imo not for story.to.design when they occupy most of the viewport which is the case here (my viewport is not that big 😄 )
![image](https://github.com/divriots/story-to-design/assets/1789748/1da5bef4-211b-46e6-b3cb-950c5bc6748c)

**Comment by muryoh** [comment]
Will look better in the next version:
![image](https://github.com/divriots/story-to-design/assets/1789748/be0015f8-7fdd-45f4-9180-cfe47fbd8b83)

**Comment by chungsi** [comment]
Wow awesome!!! Thanks for the comments as you went through this!
Definitely could change the size of the iframe on our end too, but really appreciate all the support :)
Looking forward to the next updates!

**Comment by muryoh** [comment]
New release is available - I hope your issue is fixed and if it isn't don't hesitate to reopen the issue! :pray:
