### ISSUE TITLE
(#87 follow up) Inner container doesn't shrink with outer one

### ISSUE THREAD

**Issue by alexandergrot** [divriots/story-to-design#95]
hey all, 

this is a follow up to https://github.com/divriots/story-to-design/issues/87

the original component import was fixed, but we do have a slight variation in that component which just replaces the original logo with a new logo and another link component. this seems to again break the layout and the resizing issue comes up again.

![grafik](https://github.com/divriots/story-to-design/assets/102791744/70ac1a99-16c1-4543-b52b-a179daa8ebf8)

see #87 for more details if needed

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/cTJHZkeCJCNZ1kgqi46Q/10lfwih1kpvc3h

**Comment by muryoh** [comment]
Hi @alexandergrot , sorry for the late update - we're on it!

**Comment by muryoh** [comment]
Auto-closed because an associated PR fixing it was merged, we'll try and release the fix soon! :+1:
