### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by jrgarciadev** [divriots/story-to-design#97]
## Describe the problem ##

Hey guys, huge thanks for this tool, is saving us a considerable amount of time 🙏🏻 

I got a small issue with the Tooltip component, some variants don't have any content.

![image](https://github.com/divriots/story-to-design/assets/30373425/7a5d5f8d-a63b-4907-9ee0-398872c904e2)

Please let me know if I can do something from my end to help you fix it 👍🏻 
---
Bug report identity: Please do not edit

Task path: orp7wY6YMZeNmCqtFXvm/xOAvJsDkImu8nswWlHlo/11zaa6y1jc4kq4

**Comment by gqio** [comment]
Hello @jrgarciadev 

Should be fixed with the latest release of the plugin.
Please use the `Reprocess` (to be able to reparse the story in the backend) and after `Reset canvas` to redraw in Figma.

Best.

**Comment by jrgarciadev** [comment]
It worked, thank you! @gqio
