### ISSUE TITLE
Misaligned icon and accordion active state

### ISSUE THREAD

**Issue by justinluk** [divriots/story-to-design#99]
## Describe the problem ##

Hi there,

I'm trying to import an Accordion component from Storybook and I'm noticing some bugs. 

1. For some reason the "+" icon is misaligned and also we're unable to see the active state of the accordion. 
2. Our Accordion component is using MUI's Accordion component and I believe that all it's doing to show the accordion content on click is changing a classname. There is no explicit "active" prop being passed to the component. Is there a way to show the active state of the accordion using the ":active" variant simulated by story.to.design? I tried targeting the div that contains the content for the accordion using ":actionSelector" special arg but to no avail.

Storybook Component: https://alterramtn.design/?path=/story/molecules-accordion--default&globals=backgrounds.grid:!false

![Screenshot 2023-08-28 at 3 56 08 PM](https://github.com/divriots/story-to-design/assets/158645/24949d45-27e4-4f6e-8ab1-c6b22d8ba4f4)

![Screenshot 2023-08-28 at 4 07 07 PM](https://github.com/divriots/story-to-design/assets/158645/14ba8b19-dbd0-488a-878a-a37f4e2ebf52)

---
Bug report identity: Please do not edit

Task path: R702fkgNoAQvwSdKueSF/QZnPE3HC2ud3k6wqtUro/a3vy8jkqunlh

**Comment by gqio** [comment]
Hello @justinluk 

Sorry for the issue about the icon I need to dig deeper why the `transform` is not correctly well supported here.

Regarding the second point, you can use the advanced mode to instruct the action selection.
```json
{
  "initArgs": {
    ":actionSelector": ".MuiButtonBase-root"
  },
  "variantProperties": [
    {
      "fromArg": ":tap",
      "axis": "y"
    }
  ]
}
```
and then you will end with this 

![image](https://github.com/divriots/story-to-design/assets/1063530/5fb81eb0-3c5f-478b-84fd-0be3ade8e2be)

**Comment by gqio** [comment]
Hello @justinluk 

I just had a look into the transform for the translate here... and the code path on our side is not that easy :)
I might need to wait for @gluck to get back from holidays to fix this if you don't mind (next week)

We will keep you posted
Thanks for reporting it 🙏

**Comment by justinluk** [comment]
@gqio The solution you provided for the active state works perfectly, thank you for that! We're not in a rush for a fix so when @gluck is back from holidays works great!

**Comment by justinluk** [comment]
Kudos to your team by the way, you folks always react quickly and solve our problems every single time. Easily the best support I've ever received <3

**Comment by justinluk** [comment]
Hi @gqio, do you have any updates for me about this issue? Thank you!

**Comment by gqio** [comment]
Hello @justinluk 

We are on it and we are trying to have the minimal reproduction use case for this and add it to the tests. But it takes more time than I expected.

Best.
I will keep you posted

**Comment by gqio** [comment]
Hello @justinluk 

@gluck has been busy on other topic last couple of weeks for this.

I will try to discuss it with him in the current week.

Best

**Comment by justinluk** [comment]
Thanks for the update @gluck!

**Comment by muryoh** [comment]
Hi there, we pushed a fixed internally, we'll try and release the fix soon!

**Comment by justinluk** [comment]
Awesome thank you for the update!
